= WFLY-14559 Add new attribute to control the client's WebApplicationException handlin
:author:            Ron Sigal
:email:             rsigal@redhat.com
:toc:               left
:icons:             font
:keywords:          comma,separated,tags
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.jboss.org/browse

== Overview

Since the RESTEasy context parameters were first exposed in the wildfly/jaxrs management model
(https://github.com/wildfly/wildfly-proposals/blob/main/jaxrs/WFLY-12298_Change_RESTEASY_settings.adoc)
several new parameters have been introduced, of which the following should be exposed to the user:

 * resteasy-match-cache-enabled
 * resteasy-match-cache-size
 * resteasy-patch-filter-disabled
 * resteasy-patch-filter-legacy

The wildfly/jaxrs module should be extended to expose these new parameters.

== Issue Metadata

=== Issue:

* {issue-base-url}/EAP7-1655[EAP7-1655]
* {issue-base-url}/WFLY-14559[WFLY-14559]

=== Related Issues:

* {issue-base-url}/RESTEASY-2782[RESTEASY-2782]

=== Dev Contacts:

* mailto:rsigal@redhat.com[Ron Sigal]

=== QE Contacts:

=== Testing By

Engineering

=== Affected Projects or Components:

* WildFly
* RESTEasy

== Requirements

* Some simple modifications to the wildfly/jaxrs module will be necessary to add these new parameters.
* This affects the web interface.

=== Test Plan

The proper behavior of the existing parameters is already tested. The tests in wildfly/jaxrs and
wildfly/testsuite/integration/basic just have to be extended.

== Community Documentation

The new context parameters are discussed in the RESTEasy User Guide
(https://docs.jboss.org/resteasy/docs/4.7.2.Final/userguide/html/Installation_Configuration.html#configuration_switches),

The jaxrs management model is discussed in

* in the WildFly Admin Guide
(https://github.com/wildfly/wildfly/blob/main/docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Jakarta_RESTful_Web_Services.adoc).

Nothing new is required.
