= Title
:author:            Radoslav Husar
:email:             rhusar@redhat.com
:toc:               left
:icons:             font
:keywords:          clustering,undertow,mod_cluster
:idprefix:
:idseparator:       -

== Overview

Undertow subsystem supports defining and running multiple server instances (each consisting of listeners, hosts, servlet container, etc).
At the time of writing, mod_cluster subsystem registers only the default Undertow server returned by `org.wildfly.extension.undertow.UndertowService#getDefaultServer`
to register with the proxy servers.
Different Undertow server instances might be registered with different groups of reverse proxy servers.
To support this, multiple mod_cluster configurations/profiles will be supported each associated with a specific Undertow server.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFLY-6803[WFLY-6803] WFLY-6803 Add multi-server support to mod_cluster
* https://issues.jboss.org/browse/EAP7-977[EAP7-977] Add multi-server support to mod_cluster

=== Related Issues

* https://issues.jboss.org/browse/WFLY-6634[WFLY-258] Redesign mod_cluster subsystem

=== Dev Contacts

* mailto:rhusar@redhat.com[Radoslav Husar]

=== QE Contacts

* mailto:jkasik@redhat.com[Jan Kašík]

=== Affected Projects or Components

* WildFly/EAP
* mod_cluster
* Undertow

=== Other Interested Projects

* JWS

== Requirements

=== Hard Requirements

* multiple mod_cluster configurations can be defined
* `server` can be defined for each mod_cluster configuration

=== Nice-to-Have Requirements

N/A

=== Non-Requirements

* general improvements around the subsystem codebase
* integration testing in upstream WildFly test suite

== Test Plan

The key areas for QE is the general testing of the hard requirements, i.e. being able to configure mod_cluster instances and verify the registration with the given proxies,
followed by ensuring a reasonable compatibility (from previous profiles and model operations compatibility).
