= WFLY-12221 Integrate mod_cluster subsystem with WildFly Discovery SPI
:author:            Radoslav Husar
:email:             rhusar@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

The discovery of mod_cluster load balancers (reverse proxies) can be generalized with WildFly Discovery SPI.
This essentially replaces the static proxies list (both `proxy-list` and `proxies`) which only allowed static discovery.
The general facility allows for any other form of discovery, e.g. general cloud-specific discovery.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFLY-12221[WFLY-12221 Integrate mod_cluster subsystem with WildFly Discovery SPI]
* https://issues.jboss.org/browse/EAP7-1325[EAP7-1325 mod_cluster subsystem integration with WildFly Discovery SPI]

=== Related Issues

* https://issues.jboss.org/browse/WFLY-12222[WFLY-12222 Clustering subsystems integration with WildFly Discovery SPI (tracker Jira)]
* https://issues.jboss.org/browse/EAP7-1249[EAP7-1249 Clustering subsystems integration with WildFly Discovery SPI (tracker Jira)]

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:tborgato@redhat.com[Tommasso Borgato]

=== Testing By

[ ] Engineering

[x] QE

=== Affected Projects or Components

* Project mod_cluster; but no changes in the project might be required as this solely resides in WildFly integration code.

=== Other Interested Projects

* WildFly Discovery project

== Requirements

=== Hard Requirements

* mod_cluster subsystem can reference discovery provider to be queried and registered with returned proxies
* The initial implementation, this can only be used with static list, which is currently implemented in the WildFly Discovery project
* The subsystem only ever references a single discovery provider - if multiple providers are to be used, the aggregation facility of the discovery subsystem is used.
* Capability is in place to enforce model referential integrity.

=== Nice-to-Have Requirements

* N/A

=== Non-Requirements

* N/A

//== Implementation Plan
////
Delete if not needed. The intent is if you have a complex feature which can
not be delivered all in one go to suggest the strategy. If your feature falls
into this category, please mention the Release Coordinators on the pull
request so they are aware.
////
== Test Plan

* Limited coverage might be added to WildFly's integration test suite.
* QE will provide a test plan.

== Community Documentation

This will be documented in WildFly's mod_cluster section in High-Availability guide, since this is WildFly specific and doesn't belong to
upstream project documentation (though might be linked).
