= WFCORE-3947 OCSP support in Elytron SSL truststore
:author:            Jan Kalina
:email:             jkalina@redhat.com
:toc:               left
:icons:             font
:keywords:          elytron
:idprefix:
:idseparator:       -

== Overview

Elytron provides trustmanager usable for SSL contexts used by other parts of WildFly.
It supports certificate revocations using certificate revocations list (CRL), but support of Online Certificate Status Protocol (OCSP) is required too.
This is required especially for client certificates validation.

The advantages of OCSP in comparison with CRL are:
* faster revocation (CRLs are usualy generated in constant periods)
* smaller line bandwidth needed (CRLs requires to everytime download list of all revoked nonexpired certificates)

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/EAP7-715[EAP7-715]

=== Related Issues

* https://issues.jboss.org/browse/WFCORE-3947[WFCORE-3947]

=== Dev Contacts

* mailto:jkalina@redhat.com[Jan Kalina]

=== QE Contacts

* mailto:jstourac@redhat.com[Jan Stourac]

=== Affected Projects or Components

* WildFly Core
* WildFly Elytron

//=== Other Interested Projects

== Requirements

=== Hard Requirements

* OCSP will be supported as an alternative to CRL in Elytron subsystem trustmanager (for client certificates verification).
* By default will be the OCSP responder URL obtained from the validated certificates.
* Should be possible to specify the OCSP responder (URL and certificate) manually, ignoring responder defined in certificates - for example, for needs of creating network-level caching responders.  (`responder`)
* OCSP responses should be cached. (`cache-enabled`, `cache-max-age`, `cache-max-entries`)
* Configurable timeout preventing too long waiting for unavailable OCSP responder. (`connection-timeout`)
* Configurable behavior (accept/reject) for unknown certificates. (OCSP response UNKNOWN) (boolean `accept-unknown`)
* Configurable behavior (accept/reject) for unavailable OCSP responder. (boolean `accept-when-status-unavailable`)
* If the OCSP responder is not defined in the trustmanager nor in the certificate (the certificate was issued without possibility to be revoked), the certificate has to be accepted.

=== Nice-to-Have Requirements

* OCSP would be nice on Elytron-client side too.
* OCSP requests signing is not obligatory.
* Multiple OCSP requests (to responders of different CAs) can be sent in parallel.

=== Non-Requirements

* Support of OCSP with CRL as fallback would be welcome, but is not required.

== Test Plan

* Test accepting/rejecting remoting client by good/revoked SSL certificate.
* Test behavior when OCSP server is unavailable/does not respond correctly/in time.
* Caching: test whether certificate status is cached (not requesting OCSP server again).
* Caching: test whether certificate status is updated on timeout.
* Test with invalid signature in the response.

== Community Documentation

Usage of OCSP trustmanager should be documented in some document in https://github.com/wildfly/wildfly/tree/master/docs/src/main/asciidoc/_elytron

