= WFCORE-4360 CredentialStore Backed Expression Resolution
:author:            Darran Lofthouse
:email:             darran.lofthouse@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

The present `CredentialStore` integration is implemented to provide a tight integration between the locations in the model which require access to credentials, however their is also a desire to encrypt other attribute values stored in the management model.  This enhancement is specifically to focus on that latter requirement.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFCORE-4360[WFCORE-4360]
* https://issues.jboss.org/browse/WFLY-12215[WFLY-12215]

=== Related Issues

* https://issues.jboss.org/browse/EAP7-677[EAP7-677]
* https://issues.jboss.org/browse/WFLY-11101[WFLY-11101]

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:jkasik@redhat.com[Jan Kasik]

=== Testing By

[ ] Engineering
[x] QE

=== Affected Projects or Components

Utility classes may be required within the WildFly Elytron project and will be developed as the need is identified, however the primary integration will be performed within the WildFly Core project as this enhancment is predominantly in relation to management model expression resolution.

Additionally all documentation lives within the WildFly project so updates will be applied there accordingly.

=== Other Interested Projects

== Requirements

=== Hard Requirements

The general intent for this enhancement is to develop some form of configurable expression resolver.

The expression resolver will reference a specific alias within a specific credential store, this credential will be used to decrypt the expression which was previously encrypted using this credential.

Using the credential store it will be possible to either add or generate suitable credentials to be used for the encryption / decryption of values.  This will need to include: -

 * The standalone elytron tool.
 * The management operations exposed on the credential store.

Functionality should be added to allow an administrator to encrypt a clear text String so that it can be stored as an expression, this will be added to: -

 * The standalone elytron tool.
 * New management operations, this may however be against the expression resolver not the credential store. 

The domain mode relationships will need to considered further, where we used the PicketBox vault we defined the vault within the host.xml and used it's values in the domain.xml.  As the credential store can both be defined in the host.xml and the domain.xml it would make sense to make use of the one stored within that descriptor, however this could be impacted based on how the configurable expression resolver is defined.

=== Nice-to-Have Requirements

Support for multiple expression resolvers being defined, allowing the correct one to be identified for a specific expression value.  It may not be possible to implement this in the initial enhancement however this should still be considered to allow it's potential addition at a later point.

=== Non-Requirements

This enhancement will not support the retrieval of plain text strings from the credential store, this enhancement is specifically adding support for decrypting reversibly encrypted attribute expression values.

Automatic encryption of attribute values will not be supported via this enhancement, as multiple steps are required that would be better performed within enhancements to the management tooling - each of which would require special consideration based on their own user interfaces.

As with other CredentialStore use cases no automatic replication of the store or it's entries are supported with this enhancement.

This enhancment will not add support for migrating expressions to a different credential, however if support for multiple expression resolvers is added at a later point there may be opportunities to support migration.

== Test Plan

Any utilities added to the Wildfly Elytron project will also be accompanied with their own unit tests.

The major testing of this enhancement will happen within the WildFly Core project allowing us to test in the same location it is implemented.

== Community Documentation

The CredentialStore is presently missing community documentation so before development of this enhancement can proceed this needs to be added so further enhancements can be added for this feature, this will be added under the following issue: -

* https://issues.jboss.org/browse/WFLY-11101[WFLY-11101]

The documentation will then subsequently be enhanced to include details of the new feature.

