= WFCORE-4360 CredentialStore Backed Expression Resolution
:author:            Darran Lofthouse
:email:             darran.lofthouse@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

The present `CredentialStore` integration is implemented to provide a tight integration between the locations in the model which require access to credentials, however there is also a desire to encrypt other attribute values stored in the management model.  This enhancement is specifically to focus on that latter requirement.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFCORE-4360[WFCORE-4360]
* https://issues.jboss.org/browse/WFLY-12215[WFLY-12215]

=== Related Issues

* https://issues.jboss.org/browse/EAP7-677[EAP7-677]
* https://issues.jboss.org/browse/WFLY-11101[WFLY-11101]

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:jkasik@redhat.com[Jan Kasik]

=== Testing By

[ ] Engineering

[x] QE

=== Affected Projects or Components

Changes will be required within WildFly Elytron to both provide utilities needed for this enhancement and also updates will be required within the Elytron tool to support additional key management operations and potentially offline encryption of values.
 
Beyond this the primary integration will be performed within the WildFly Core project as this enhancement is predominantly in relation to management model expression resolution.

Additionally all documentation lives within the WildFly project so updates will be applied there accordingly.

=== Other Interested Projects

== Requirements

=== Hard Requirements

The general intent for this enhancement is to develop some form of configurable expression resolver.

The expression resolver will reference a specific alias within a specific credential store, this credential will be used to decrypt the expression which was previously encrypted.  The expression resolver will also contain configuration such as the algorithm to use.

At all stages where installed `java.security.Provider` instances are used to obtain implementation it must remain possible to make use of alternative / custom provider implementations without being restricted exclusively to the implementations provided with the Java environment.

The enhancement will exclusively make use of `javax.crypt.SecretKey` instances generated from a `javax.crypto.SecretKeyFactory`, these will be stored in a `CredentialStore`.

For the purpose of this enhancement each of the secret key types specified in <<https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#secretkeyfactory-algorithms, Java Security Standard Algorithm Names>> for Java 11 will be supported, however a user will be restricted to using the subset supported by their own JVM / installed `java.security.Provider` instances.

It will be possible to generate, export, and import the SecretKey instances using both the command line tool and management operations.

The Elytron tool `credential-store` command already has an `--add` action, rather than overloading this action for different types of key and different operations which will become complex very quickly a new set of actions will be added: -

 * `--generate-secret-key`
 * `--export-secret-key`
 * `--import-secret-key`  

The exact parameters are still to be evolved, however in all cases it is expected the alias and type of the key will need to be specified.  Parameters will also need to be defined to provide values needed for any `java.security.spec.KeySpec` which is required for the operation.  The import and export actions will make use of Base64 encodings of the key.

It is not feasible for all actions to have a short form so these new actions will have a long form only, within the tool we should try and restrict the use of the short form for parameters only.

A similar approach will also be taken for the management operations against the credential store, presently the resource contains an `add-alias` operation which can be used to add a credential based on a clear text String.  The following operations will be added to the `credential-store` resource: -

 * `generate-secret-key`
 * `export-secret-key`
 * `import-secret-key`
 
Within the management model operations are self describing so making use of dedicated operations makes it easier for tooling to present a meaningful UI to end users automatically.

As with the command line utility it is expected each of these will need to take the alias and key type as a parameter, additionally values needed for a `java.security.spec.KeySpec` will need to be specified.

Overall regarding `KeySpec` instances I expect we will define a set of supported types and define parameters that allow for their selection, should custom or alternative key factories be used to operate successfully it will be a requirement that they can make use of the standard key specs.

NOTE: The credential store also offers a programatic API, should the tooling and operations be insufficient for an end user manual population of the credential store may remain an option.

The expression resolver should support both generated keys and password based encryption.

Using the credential store it will be possible to either add or generate suitable keys to be used for the encryption / decryption of values.  This will need to include: -

 * The standalone elytron tool.
 * The management operations exposed on the credential store.

Where generated keys are used the tools and management operations should support exporting and importing the keys to allow them to be 'moved' between credential stores.  Where possible this should be achieved using specification defined formats.

Functionality should be added to allow an administrator to encrypt a clear text String so that it can be stored as an expression, this will be added to: -

 * The standalone elytron tool.
 * New management operations, this may however be against the expression resolver not the credential store. 

The domain mode relationships will need to considered further, where we used the PicketBox vault we defined the vault within the host.xml and used it's values in the domain.xml.  As the credential store can both be defined in the host.xml and the domain.xml it would make sense to make use of the one stored within that descriptor, however this could be impacted based on how the configurable expression resolver is defined.

=== Nice-to-Have Requirements

It would also be beneficial to support Public / Private Key Pairs, in this case a public key from the server can be used to encrypt the value leaving it decryptable using the private key, this will have a benefit that giving a user the ability to encrypt a value does not give them the ability to decrypt that value.  If we are to support private key encryption the credential store does not presently support the storage of private keys unless they are either paired with their public key or are associated with an X509 certificate - individual private key storage may become desirable.

This enhancement should be usable with third party cryptographic providers such as BouncyCastle, the verification of this would likely be an independent step.

We should consider deprecating the `--add` operation for the `credential-store` command on the Elytron tool and instead adding an `--add-password` operation to being this in alignment with the operations being used for keys.  As passwords are not generated equivalent import / export operations would not be required. 

Support for multiple expression resolvers being defined, allowing the correct one to be identified for a specific expression value.  It may not be possible to implement this in the initial enhancement however this should still be considered to allow it's potential addition at a later point.

It would be nice to cross reference subsystem managed security providers for the expression resolver, however this component needs to be usable at the start of `Stage.RUNTIME` so there will be a limit as to how many subsystem managed resources can be depended upon.

=== Non-Requirements

This enhancement will not support the retrieval of plain text strings from the credential store, this enhancement is specifically adding support for decrypting reversibly encrypted attribute expression values.

Automatic encryption of attribute values will not be supported via this enhancement, as multiple steps are required that would be better performed within enhancements to the management tooling - each of which would require special consideration based on their own user interfaces.

As with other CredentialStore use cases no automatic replication of the store or it's entries are supported with this enhancement.

This enhancement will not add support for migrating expressions to a different credential, however if support for multiple expression resolvers is added at a later point there may be opportunities to support migration.

This enhancement is only in relation to expression resolution within the application server's management model - this does not extend to any other descriptors or configuration files.

Expression resolution will only be supported against attributes that already support expression resolution, this enhancement will not perform a review of which attributes support expression resolution and will not be changing any attributes to support expression resolution.

== Implementation Plan

A large portion of this enhancement is going to be in relation to the addition of the expression resolver within the management model and demonstrating the viability of the approach for this reason the implementation will be divided into two stages.

=== Hard Requirements

A first pass of the implementation will focus exclusively on the defined "Hard Requirements" this will result in an end to end delivery of the enhancement.

=== Nice-to-Have Requirements

The nice to have requirements are effectively additional enhancements that can be added to this work such as alternative key types etc..

After the hard requirements have been implemented we will make a decision as to which of the nice to have requirements we will also include in this work, a part of this decision process will take into account any upcoming feature freeze deadlines.  This enhancement can be considered complete once the hard requirements have been implemented, if any of the nice to have requirements have not been included in the enhancement we will consider raising future feature requests to further enhance this in a later stage.

== Test Plan

Any utilities added to the Wildfly Elytron project will also be accompanied with their own unit tests.

The major testing of this enhancement will happen within the WildFly Core project allowing us to test in the same location it is implemented.

== Community Documentation

The CredentialStore is presently missing community documentation so before development of this enhancement can proceed this needs to be added so further enhancements can be added for this feature, this will be added under the following issue: -

* https://issues.jboss.org/browse/WFLY-11101[WFLY-11101]

The documentation will then subsequently be enhanced to include details of the new feature.

The documentation must sufficiently describe the encryption process to a level which would allow users and third parties to create their own tooling to generate the expressions.  They may wish to accomposh this using Java however they may also choose to do so in alternative languages provided the required cipher algorithms are available.

