= WFCORE-3970 Add support for Elytron's ldap-key-store to be dynamically reloaded
:author:            Justin Michael Cook
:email:             jucook@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.jboss.org/browse

== Overview

It is not currently possible to reload the certificates dynamically for Elytron's ldap-key-store, requiring WildFly to be restarted in order to see any changes done in the LDAP directory. This feature is currently available for simple file based keystores with the load operation. This task is to add similar support for the ldap-key-store.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFCORE-3970[WFCORE-3970]

=== Related Issues

* https://issues.jboss.org/browse/EAP7-1052[EAP7-1052]

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:msvehla@redhat.com[Martin Švehla]

=== Affected Projects or Components

* WildFly, Security

=== Other Interested Projects

== Requirements

=== Hard Requirements

* When changes are made to certificates in the LDAP directory, it should be possible to reload these certificates dynamically without having to restart the server. This should be done by adding a load operation to the Elytron subsystem's ldap-key-store resource. This new management operation will not take any parameters and will be a runtime only operation akin to the key-store load operation.
* A similar operation should also be added to the Elytron subsystem's filtering-key-store resource so the underlying keystore it is based on does not have to be reloaded.

[source,bash]
/subsystem=elytron/ldap-key-store=LDAP_KEY_STORE_NAME:load()

=== Nice-to-Have Requirements

=== Non-Requirements

== Test Plan

Tests to run the new CLI operation will be added.

== Community Documentation

This new management operation will be documented in the WildFly documentation under Using the Elytron subsystem.