= WFCORE-4360 CredentialStore Backed Expression Resolution
:author:            Darran Lofthouse
:email:             darran.lofthouse@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

The present `CredentialStore` integration is implemented to provide a tight integration between the locations in the model which require access to credentials, however there is also a desire to encrypt other attribute values stored in the management model.  This enhancement is specifically to focus on that latter requirement.

This first implementation is going to focus exclusively on supporting `AES` key types and encryption.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFCORE-4360[WFCORE-4360]
* https://issues.jboss.org/browse/WFLY-12215[WFLY-12215]
* https://issues.jboss.org/browse/ELY-1842[ELY-1842] - Command line support for `SecretKey` manipulation.

=== Related Issues

* https://issues.jboss.org/browse/EAP7-677[EAP7-677]
* https://issues.jboss.org/browse/WFLY-11101[WFLY-11101]

=== Other Links

The following is a link to a discussion on the mailto:wildfly-dev@lists.jboss.org[wildfly-dev] mailing list.

https://lists.jboss.org/pipermail/wildfly-dev/2019-July/006932.html[Expression Resolver Discussion]

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:jkasik@redhat.com[Jan Kasik]

=== Testing By

[ ] Engineering

[x] QE

=== Affected Projects or Components

Changes will be required within WildFly Elytron to both provide utilities needed for this enhancement and also updates will be required within the Elytron tool to support additional key management operations and potentially offline encryption of values.
 
Beyond this the primary integration will be performed within the WildFly Core project as this enhancement is predominantly in relation to management model expression resolution.

Additionally all documentation lives within the WildFly project so updates will be applied there accordingly.

=== Other Interested Projects

== Requirements

=== Hard Requirements

The general intent for this enhancement is to develop some form of configurable expression resolver.

The expression resolver will reference a specific alias within a specific credential store, this credential will be used to decrypt the expression which was previously encrypted.  The expression resolver will also contain configuration such as the algorithm to use.

At all stages where installed `java.security.Provider` instances are used to obtain implementation it must remain possible to make use of alternative / custom provider implementations without being restricted exclusively to the implementations provided with the Java environment.

==== Credential Store

This enhancement will exclusively make use of `AES` `javax.crypt.SecretKey` instances, these do not require the use of a `javax.crypto.SecretKeyFactory` and can be generated using random key material directly using the `javax.crypto.spec.SecretKeySpec` class.  The generated `SecretKey` will be stored in a `CredentialStore`.

It will be possible to generate, export, and import the SecretKey instances using both the command line tool and management operations.

The Elytron tool `credential-store` command already has an `--add` action, rather than overloading this action for different types of key and different operations which will become complex very quickly a new set of actions will be added: -

 * `--generate-secret-key`
 * `--export-secret-key`
 * `--import-secret-key`  

The `--generate-secret-key` action will take the alias to store the key as an argument in the same pattern as `add` it will also take the following additional option: -

 * `--size` - The key size (number of bits) - acceptable values 128, 192, or 256 - default 256.
 
The `--export-secret-key` action will take the alias of the previously stored key as an argument, no further option will be required.

The `--export-secret-key` action will return a single Base64 value which is the key in it's encoded form.

The `--import-secret-key` action will take the alias to store the key as an argument, it will also take the following additional option: -

 * `--key` - The key to import encoded using Base64.

If the `--key` option is not specified the user will be prompted to enter the key interactively, this will avoid the key being seen in the current running processes and avoid the key being cached in the users command line history.

NOTE: For `generate-secret-key` and `import-secret-key` if an entry already exists for that alias / algorithm combination the behaviour will be the same as the `add` action in relation to replacing the entry or reporting an error.  (To be checked)

For this specific enhancement where an algorithm is required for the `SecretKey` we will use the hard coded value of `AES`, if later enhancement add support for further key types then it may be necessary for an optional `algorithm` argument / parameter to be added to each of the above commands / operations.  Should an `algorithm` argument be added at a later point it would be optional and default to `AES` for backwards compatibility.

It is not feasible for all actions to have a short form so these new actions will have a long form only, within the tool we should try and restrict the use of the short form for parameters only.

A similar approach will also be taken for the management operations against the credential store, presently the resource contains an `add-alias` operation which can be used to add a credential based on a clear text String.  The following operations will be added to the `credential-store` resource: -

 * `generate-secret-key`
 * `export-secret-key`
 * `import-secret-key`
 
Within the management model operations are self describing so making use of dedicated operations makes it easier for tooling to present a meaningful UI to end users automatically.

The `credential-store` resource already contains a `remove-alias` operation however this assumes the type of the credential is `PasswordCredential` a new attribute will be added to this operation `entry-type` which will default to `PasswordCredential` but will also accept `SecretKeyCredential` as a value allowing credentials of type `SecretKeyCredential` to be removed from the credential store.

As with the command line utility it is expected each of these will need to take the alias as a parameter.

NOTE: The credential store also offers a programatic API, should the tooling and operations be insufficient for an end user manual population of the credential store may remain an option.

==== Command Line Encryption

Whilst the Elytron tool does contain a `credential-store` command the encryption of values is really a special operation so a new command `encryption` will be added to the tool.

When using the new `encryption` command it will be necessary to reference an existing `alias` within an existing `credential-store` to obtain an instance of the `SecretKey` that will be used for encryption of a plain text String, this command will make use of the same attributes as used by the `credential-store` command to identify the store and alias to use to load the key.  This is important so that using different commands in the same command line utility is consistent.

The encryption of String instances will make use of `javax.crypto.Cipher` APIs, although the only `SecretKey` type supported will be `AES` various transformations will be supported, a transformation can be specified in the format: -

    Algorithm Name/Algorithm Mode/Padding

The support algorithm names will be: -

 * `AES`
 * `AES_128`
 * `AES_192`
 * `AES_256`

The final three names restrict the algorithm to the specified key size.

The supported modes will be: -

 * `CBC`
 * `CTR`
 * `GCM`
 
The following padding will be supported: -

 * `NoPadding`
 * `PKCS5Padding`

Different permutations of name, mode, and padding require different `ParameterSpec` instances to configure the `Cipher`, by defining the supported set in advance selection of the correct `ParameterSpec` can be more deterministic.

If no cipher is specified the tool will default to `????`.

The new `encryption` command will support two actions: -

 * `--encrypt` - To encrypt a value and return the result Base64 encoded.
 * `--create-expression` - To encrypt a value and return it as a complete expression.
 
In both cases the value to be encrypted can be passed in with the action or if not specified the user will be prompted to enter the value.  In the case of `--create-expression` the user can also optionally specify the `resolver` that will be used to create the expression String.

The following arguments can also be specified to both actions: -

 * `--iv-length` - The size in bytes of the initialisation vector, valid range <12,16> with a default of 12.
 * `--authentication-tag-length` - The length of the authentication tag in bits, only applicable for the `GCM` mode.  Default 128.

The tool will not add any support for the decryption of expressions or their values.


==== Expression Resolver

Presently WildFly Core supports an expression resolver that can delegate to a Vault configuration and if that is not available fall back to use either system properties or environment variables.  This will be updated to make use of the `CapabilityRegistry` and attempt to lookup a capability using a pre-defined constant (To be defined) which exposes an expression resolver runtime API.  The expression resolver looked up using a capability will be used first to attempt to resolve any expression, if this is successful the resolved value will be used - if not we will fallback to the existing behaviour of using the vault and if that fails using a system property or environment variable.

A new singleton resource will be added to the elytron subsystem called `expression=encryption` the purpose of this resource is to contain the configuration both for the encryption and decryption of values.  As a singleton we know only one instance of this resource can be defined within the subsystem reducing some of the complexity multiple instances would cause.  The resource will contain the definition of one or more resolvers to decrypt the inline expressions.

The format of the expressions resolved using the WildFly Elytron expression resolver will be `${ENC:Resolver:ENCRYPTED_DATA}` where `Resolver` is a reference to the specific resolver defined in the `expression=encryption` resource and `ENCRYPTED_DATA` is the data to be decrypted encoded using Base64.

The `expression=encryption` resource will register it's expression resolver capability with the `CapabilityRegistry` making it available for runtime resolution of expressions.

The `expression=encryption` resource will contain three attributes, the first attribute being `resolvers` which will be used to define one or more resolvers to handle the encryption and decryption of values.  Each resolver will support the following configuration: -

 * Reference to a credential store and alias to identify a specific previously created `SecretKey` to use.
 * Name of the algorithm to use for the encryption / decryption.
 * Any additional parameters such as `salt`, `iteration count` etc.. as required to configure the algorithm.

The second attribute on the `expression=encryption` resource will be `default-resolver` which will be used to optionally specify which resolver is the default, the expression can then be simplified to `${ENC:ENCRYPTED_DATA}`.

As expressions are already widely in use with the application server there is a small possibility that users may have already defined expressions with a prefix of `ENC:` expecting it to be resolved as a system property.  The `expression=encryption` resource will also have a third attribute `prefix` attribute which will allow an alternative prefix to `ENC` to be specified.

The `expression=encryption` resource will also contain an operation `create-expression` the purpose of this operation being to take a clear text value and using one of the defined `resolvers` output an expression that can be used elsewhere in the management model.  The operation will just require two parameters: -

 * `resolver` - The name of the defined resolver to use to encrypt the data, if the `expression=resolver` resource has the `default-resolver` attribute defined this parameter can be omitted.
 * `data` - The clear text value to be encrypted.

The return value of the operation will be the complete expression ready to be used elsewhere in the mode.

We will not support the decryption of expressions other than the support within the management model to resolve existing expressions.



==== Base64 Representations

Base64 representations will be used for both the export and import of the generated keys and for the expression value to be passed to the expression resolver - generally these details should be opaque to the end user however we may include the description within the documentation allowing for others to make use of the format.  We should consider that in the future alternative representations may be required either to support alternative key types or to support alternative representations so the representations will also be versioned.

The general structure of the first representation will be (illustrated as an array): -

    { 'E', 'L', 'Y', (VERSION), (TYPE), VALUE... }

For the changes being made for this enhancement the version will be `1`.  For each of the supported commands and operations should a representation with a version other than `1` an error will be reported. 

A generated `SecretKey` will be encoded with a type of 1: -

    { 'E', 'L', 'Y', (VERSION), 1, KEY... }

As version `1` of this implementation only supports `AES` `SecretKey` instances it is not necessary for the key algorithm to be encoded within this representation, additionally the key size does not need to be specified as it will be detectable from the length of the actual key.

An encrypted expression will be encoded with a type of 2: -

    { 'E', 'L', 'Y', (VERSION), 2, IV Length, Initialisation Vector, Cipher Text }

At the moment only a single version of the representation will be supported, in the future the commands and operations that generated the encoded values may take a parameter to specify which version to generate however that is not required within the first implementation.  Additionally later versions of the tooling and operations should always attempt to use the oldest version possible to encode a value allowing newer tools to encode values for use by older versions.

These representations are independent of the overall representation of the expressions as it is intended a portion of those expressions is both human readable and modifiable to allow alternative resolver definitions to be used without requiring the Base64 representation to be recreated. 

==== Domain Mode

The domain mode relationships will need to considered further, where we used the PicketBox vault we defined the vault within the host.xml and used it's values in the domain.xml.  As the credential store can both be defined in the host.xml and the domain.xml it would make sense to make use of the one stored within that descriptor, however this could be impacted based on how the configurable expression resolver is defined.


=== Nice-to-Have Requirements

It would also be beneficial to support Public / Private Key Pairs, in this case a public key from the server can be used to encrypt the value leaving it decryptable using the private key, this will have a benefit that giving a user the ability to encrypt a value does not give them the ability to decrypt that value.  If we are to support private key encryption the credential store does not presently support the storage of private keys unless they are either paired with their public key or are associated with an X509 certificate - individual private key storage may become desirable.

This enhancement should be usable with third party cryptographic providers such as BouncyCastle, the verification of this would likely be an independent step.

We should consider deprecating the `--add` operation for the `credential-store` command on the Elytron tool and instead adding an `--add-password` operation to being this in alignment with the operations being used for keys.  As passwords are not generated equivalent import / export operations would not be required. 

Support for multiple expression resolvers being defined, allowing the correct one to be identified for a specific expression value.  It may not be possible to implement this in the initial enhancement however this should still be considered to allow it's potential addition at a later point.

It would be nice to cross reference subsystem managed security providers for the expression resolver, however this component needs to be usable at the start of `Stage.RUNTIME` so there will be a limit as to how many subsystem managed resources can be depended upon.

A lot of the arguments passed into the command line tool are repeated on each invocation, a configuration file containing these to avoid repetition may be beneficial - I suspect however that may be an independent enhancement.

=== Non-Requirements

This enhancement will not support the retrieval of plain text strings from the credential store, this enhancement is specifically adding support for decrypting reversibly encrypted attribute expression values.

Automatic encryption of attribute values will not be supported via this enhancement, as multiple steps are required that would be better performed within enhancements to the management tooling - each of which would require special consideration based on their own user interfaces.

As with other CredentialStore use cases no automatic replication of the store or it's entries are supported with this enhancement.

This enhancement will not add support for migrating expressions to a different credential, however if support for multiple expression resolvers is added at a later point there may be opportunities to support migration.

This enhancement is only in relation to expression resolution within the application server's management model - this does not extend to any other descriptors or configuration files.

Expression resolution will only be supported against attributes that already support expression resolution, this enhancement will not perform a review of which attributes support expression resolution and will not be changing any attributes to support expression resolution.

Custom expression resolver implementations are outside of the scope of this RFE, adding custom implementations which potentially reference a credential store could be a future enhancement.

Resolved expressions are a deliberate decision to move values from the model to an alternative expression resolver, it is not possible to determine the expression resolution capabilities of a slave.  Where credential store backed expression resolution is in place transformers will not reject sending those expressions to the slave.  However as the `expression=encryption` resource is not supported on the slave that will by itself fail transformation and be rejected.

== Implementation Plan

A large portion of this enhancement is going to be in relation to the addition of the expression resolver within the management model and demonstrating the viability of the approach for this reason the implementation will be divided into two stages.

=== Hard Requirements

A first pass of the implementation will focus exclusively on the defined "Hard Requirements" this will result in an end to end delivery of the enhancement.

=== Nice-to-Have Requirements

The nice to have requirements are effectively additional enhancements that can be added to this work such as alternative key types etc..

After the hard requirements have been implemented we will make a decision as to which of the nice to have requirements we will also include in this work, a part of this decision process will take into account any upcoming feature freeze deadlines.  This enhancement can be considered complete once the hard requirements have been implemented, if any of the nice to have requirements have not been included in the enhancement we will consider raising future feature requests to further enhance this in a later stage.

== Test Plan

Any utilities added to the Wildfly Elytron project will also be accompanied with their own unit tests.

The major testing of this enhancement will happen within the WildFly Core project allowing us to test in the same location it is implemented.

== Community Documentation

The CredentialStore is presently missing community documentation so before development of this enhancement can proceed this needs to be added so further enhancements can be added for this feature, this will be added under the following issue: -

* https://issues.jboss.org/browse/WFLY-11101[WFLY-11101]

The documentation will then subsequently be enhanced to include details of the new feature.

The documentation must sufficiently describe the encryption process to a level which would allow users and third parties to create their own tooling to generate the expressions.  They may wish to accomposh this using Java however they may also choose to do so in alternative languages provided the required cipher algorithms are available.

