---
categories:
- security
- elytron
- wf-galleon
stability-level: default
issue: https://github.com/wildfly/wildfly-proposals/issues/21717
feature-team:
 developer:
 - skyllarr
 sme:
  - darranl
 outside-perspective:
  - honza-kasik
promotes: https://github.com/wildfly/wildfly-proposals/pull/810
promoted-by: skyllarr
---

= Promote WildFly Vault feature-pack and hashicorp-vault layer/subsystem to default stability
:author:            Diana Krepinska
:email:             dvilkola@ibm.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -


== Overview

The https://github.com/wildfly-security-incubator/wildfly-vault-feature-pack[WildFly Vault feature-pack] (HashiCorp Vault integration) delivers a Galleon feature-pack and a `hashicorp-vault` subsystem that lets administrators define Vault-backed credential stores, manage aliases, and resolve `+$\{HC_VAULT::...\}+` expressions against those stores. The feature-pack is currently in community stability levels.

=== User Stories

* As an administrator, I want to use HashiCorp Vault as an external secrets storage

== Issue Metadata

- *WildFly JIRA:* https://issues.redhat.com/browse/WFLY-21717[WFLY-21717]

=== Related Issues

- https://issues.redhat.com/browse/ELY-1897[ELY-1897]
- https://issues.redhat.com/browse/WFLY-21717[WFLY-21717]
- https://issues.redhat.com/browse/WFLY-21572[WFLY-21572]
- https://redhat.atlassian.net/browse/WFCORE-7603[WFCORE-7603]
- https://redhat.atlassian.net/browse/EAP7-2375[EAP7-2375]

=== Affected Projects or Components

- https://github.com/wildfly-security-incubator/wildfly-vault-feature-pack[wildfly-vault-feature-pack] (feature-pack impl, tests)
- https://github.com/wildfly-security-incubator/wildfly-elytron-hashicorp-vault[wildfly-elytron-hashicorp-vault] (core elytron integration)
- https://github.com/wildfly/wildfly[wildfly] (documentation)
- https://github.com/wildfly/wildfly-galleon-feature-packs[wildfly-galleon-feature-packs]

=== Other Interested Projects

=== Relevant Installation Types

* Traditional standalone server (unzipped or provisioned by Galleon)
* Managed domain
* OpenShift Source-to-Image (S2I)
* Bootable JAR

== Requirements

The functional requirements are unchanged from the community-level feature; only the **stability** and **delivery method** change.

There are more options as to where this feature-pack and a layer could be located. We can either maintain it as a separate feature-pack, or add the layer under the wildfly-ee feature-pack or elsewhere.

Argument to keep it as a separate feature-pack was based on the fact that it might later contain more external secret storages than just HashiCorp Vault, which will probably require more 3rd party libraries to be used. This might lead to having to release updates at various times. But note that this would NOT help with the application server's schedule, as the FP would need to be updated in the manifest which forces to keep the schedule anyway.

Given the additional cost of maintaining separate feature-pack, and no good reason identified to keep it separate, the `hashicorp-vault` layer will be included within the `wildfly-ee` feature-pack.

The `hashicorp-vault` modules will be included in the default server ZIP, but the layer/subsystem will not be included in the default server configuration. So it will be possible to use the management operations to add hashicorp vault extension by referencing this module, but it won't be part of the default configuration.

Requirements copied from community stability proposal:

=== Credential store

* The feature-pack must provide a new subsystem (eg. `hashicorp-vault` subsystem) with a `credential-store` resource type.
* Credential store will be able to connect to a HashiCorp Vault server and authenticate with one of the following methods:

** token via credential-reference
** certificate authentication thanks to the ssl-context configured in the authentication-context attribute
* TLS for the connection to Vault must be configurable (e.g. via authentication-context) so that server and client certificates can be used.
* The credential store must implement the Elytron credential store SPI so that it is usable everywhere where elytron credential store resources are usable.
* Credential store management operations must be supported as usual: add credential store, remove credential store, add-alias, remove-alias, read-aliases
* The feature-pack must be integrated with GLOW and be discoverable.

=== Expression resolver

* An expression resolver must support expressions that resolve to secrets stored in a configured Vault credential store.
* Expression format can for example be `${HC_VAULT::store-name:alias}`. Resolution occurs at RUNTIME.
* All attributes in management model that support expression resolution can use these Vault e

=== Changed requirements

* No dedicated feature-pack, instead the layer is moved under the wildfly-ee feature-pack
* Localisation will be achieved by having dedicated product branches where the translated texts will be added

=== Non-Requirements

- quickstart is not required
- client side impl. is not required, upstream feature request was created: https://redhat.atlassian.net/browse/WFCORE-7603
- HAL feature request: https://redhat.atlassian.net/browse/EAP7-2375

=== Future Work

* See opened issues here https://github.com/orgs/wildfly-security-incubator/projects/1/views/1

== Backwards Compatibility

* Existing configurations that were created at community stability should continue to work

=== Default configuration

* none

=== Importing existing configuration

* none

=== Deployments

* Feature not applicable to deployments.

=== Interoperability

* HashiCorp Vault can be used as an external secrets storage that WildFly accesses

== Implementation Plan

. Update the **wildfly-vault-feature-pack** so subsystem extensions, XML schemas, and Galleon feature-pack metadata use **default** stability.
. Update **WildFly / Elytron documentation** and **release notes** to remove preview stability mentions and document wildfly-ee feature-pack

== Admin Clients

* `jboss-cli` and the management API continue to administer `subsystem=hashicorp-vault` if the layer was provisioned
* HAL/console can add credential stores

== Security Considerations

* same as in previous proposal

[[test_plan]]
== Test Plan

* QE approval
* Automated tests in **wildfly-vault-feature-pack** (subsystem + integration) and in wildfly repository (microprofile TCK testsuite used as a template).
* Manual tests against HC Vault running locally.

== Community Documentation

* Update WildFly documentation so the feature is described at **default** stability and document wildfly-ee feature-pack.

== Release Note Content

WildFly now supports the `hashicorp-vault` layer at **default stability**, allowing Galleon provisioning of the `hashicorp-vault` layer and configuration of Vault-backed credential stores and encrypted expressions.
