= WFCORE-1110 Custom HTTP Headers for the HTTP Management Interface
:author:            Darran Lofthouse
:email:             darran.lofthouse@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

The HTTP management endpoint of the application server already returns a pre-defined set of HTTP headers in all of the responses that are sent to the clients, however it is sometimes desirable that additional headers can be returned to satisfy the requirements of an environment the application server is installed within.  This enhancement is to add support for an end user to specify a custom set of HTTP headers that should be returned within each response.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFCORE-1110[WFCORE-1110]

=== Related Issues

* https://issues.jboss.org/browse/WFLY-12787[WFLY-12787]
* https://issues.jboss.org/browse/EAP7-1335[EAP7-1335]
=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:tterem@redhat.com[Tomas Terem]

=== Testing By
// Put an x in the relevant field to indicate if testing will be done by Engineering or QE. 
// Discuss with QE during the Kickoff state to decide this
[ ] Engineering

[X] QE

=== Affected Projects or Components

=== Other Interested Projects

== Requirements

=== Hard Requirements

The HTTP management interface provides access to a number of contexts, our primary contexts are accessed at the following paths: -

 * `/management` - The endpoint for servicing management requests over HTTP.
 * `/console` - The endpoint to provide the admin console initial page and complete JavaScript.
 
Subsystems can also dynmically register additional contexts to dynamically provide additional functionality or content over the HTTP management interface. 

As we have different endpoints it may be desirable for them to return different headers, as an example some headers are only applicable to the handling of pages or interpretation of the JavaScript so should only be applied to the `/console` endpoint whilst other headers may be applicable to both.

Configuration will be added to the HTTP management endpoint to allow headers to be specified, an example configuration will be added later but in general the following will be apply: -

 * The configuration will allow an end user to specify headers to be added based on a specified path prefix.
 * This will be a new `custom-headers` attribute on the `/core-service=management/management-interface=http-interface` resource.
 * Within the `custom-headers` attribute it will be possible to specify a set of headers using key / value pairs against a specific path.
 * All paths will be assumed to be prefixes starting with `/` - any paths missing a leading `/` will be handled as though the leading `/` has been specified.
 * If a specific header is defined multiple times it will be added to the response multiple times.
 * Configured headers will not override any headers added by the corresponding endpoint.

=== Nice-to-Have Requirements

=== Non-Requirements

As the contexts supported by the HTTP management interface can be added dynamically by subsystems no validation will be performed to verify that the specified paths are genuinely reachable paths as this information is not available to us at the time we perform model validation.

== Test Plan

== Community Documentation

Community documentation will need to be added describing how to configure custome HTTP headers that should be returned on every request.

== Release Note Content

TODO

////
Draft verbiage for up to a few sentences on the feature for inclusion in the
Release Note blog article for the release that first includes this feature. 
Example article: http://wildfly.org/news/2018/08/30/WildFly14-Final-Released/.
This content will be edited, so there is no need to make it perfect or discuss
what release it appears in.  "See Overview" is acceptable if the overview is
suitable. For simple features best covered as an item in a bullet-point list 
of features containing a few words on each, use "Bullet point: <The few words>" 
////
