= Hibernate ORM 6 Jakarta Persistence 3.1
:author:            Scott Marlow
:email:             smarlow@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

Support Persistence 3.1 by including Hibernate ORM 6.1.x https://issues.redhat.com/browse/WFLY-15440/[WFLY-15440] + https://issues.redhat.com/browse/EAP7-1815[EAP7-1815].  Also update the WildFly Persistence Container to support Jakarta Persistence 3.1.

The list of databases to test with are in comments on https://issues.redhat.com/browse/EAP7-1820.

Hibernate ORM 6.1 https://github.com/hibernate/hibernate-orm/releases/tag/6.1.0[ORM 6.1.0] is required instead of Hibernate ORM 6.0.x, due to the https://issues.redhat.com/browse/WFLY-16552[Security Manager changes] + https://issues.redhat.com/browse/WFLY-16959[Jandex 3 support].

Hibernate Search needs to be upgraded to 6.1 as per https://issues.redhat.com/browse/WFLY-15838/[WFLY-15838] + https://issues.redhat.com/browse/EAP7-1816[EAP7-1816]

The new libraries were added for Jakarta EE 10 compatibility (https://jakarta.ee/compatibility/certification/10).

Migration notes for transition from Hibernate ORM 5.3 to 6.1 can be viewed via, these pages will be used as input for the EAP 8 documentation updates:

* https://github.com/hibernate/hibernate-orm/blob/5.4/migration-guide.adoc
* https://github.com/hibernate/hibernate-orm/blob/5.5/migration-guide.adoc
* https://github.com/hibernate/hibernate-orm/blob/5.6/migration-guide.adoc
* https://github.com/hibernate/hibernate-orm/blob/6.0/migration-guide.adoc
* https://github.com/hibernate/hibernate-orm/blob/6.1/migration-guide.adoc

== Issue Metadata

=== Dev Contacts

* mailto:{Scott Marlow}[{smarlow@redhat.com}] JPA / WildFly integration lead
* mailto:{Paul Ferraro}[{pferraro@redhat.com}] WildFly clustering lead
* mailto:{Steve Ebersole}[{steve@hibernate.org}] Hibernate ORM, project lead
* mailto:{Sanne Grinovero}[{sanne@hibernate.org}] Hibernate team lead


=== Other Interested Projects

Infinispan project will support the Hibernate ORM 6 second level cache interfaces (SPI) which are compatible with the Hibernate ORM 5.3 second level cache interfaces (SPI) so that EAP 8 users can use a Persistence 2nd Level Cache.

== Requirements

Included JPA 3.1, Hibernate ORM 6.1+, Hibernate Search 6.1+.

== Test Plan

The Jakarta EE 10 TCKs must be passed with the upgraded Hibernate ORM version.

* The Hibernate ORM testsuite must be passed against each supported database listed in https://issues.redhat.com/browse/EAP7-1820
* Note that (SAP) Sybase SQL Server cannot be tested currently in the community since there is no (community) JDBC driver for Sybase SQL Server (Adaptive Server Enterprise) so this should be tested as soon as possible.
* TCK testing needs to pass.


The Hibernate ORM tests in the Hibernate ORM project must be passed against the following database servers for EAP 8:
* IBM DB2 version 11.5
* Oracle version 21c
* MySQL version 8.0
* MariaDB version version 10.8
* MariaDB Galera Cluster versions Galera 4 + MariaDB 10.8
* Microsoft SQL Server version 2019
* PostgreSQL version 14.4
* EnterpriseDB Advanced Server version 14.4
* (Sybase) SAP ASE (Adaptive Server Enterprise version) 16.0

