= Add http-custom-mechanism to the EAP quickstarts
:author:            Farah Juma
:email:             fjuma@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

The http-custom-mechanism quickstart is currently a community-only quickstart because it's not part of the EAP quickstarts repo.
Nothing else demonstrates how to configure this so it should be added to the EAP quickstarts as well.

== Issue Metadata

=== Issue

* https://issues.redhat.com/browse/EAP7-1940[EAP7-1940]
* https://issues.redhat.com/browse/WFLY-16471[WFLY-16471]

=== Related Issues


=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

=== Testing By
// Put an x in the relevant field to indicate if testing will be done by Engineering or QE. 
// Discuss with QE during the Kickoff state to decide this
* [ ] Engineering

* [ ] QE

=== Affected Projects or Components

=== Other Interested Projects

=== Relevant Installation Types
// Remove the x next to the relevant field if the feature in question is not relevant
// to that kind of WildFly installation
* [x] Traditional standalone server (unzipped or provisioned by Galleon)

* [ ] Managed domain

* [ ] OpenShift s2i

* [x] Bootable jar

== Requirements

=== Hard Requirements

* The https://github.com/wildfly/quickstart/tree/main/http-custom-mechanism[http-custom-mechanism] quickstart will be added to the EAP 8 Quickstarts
deliverable, i.e. it will be included in the Quickstarts zip distribution and in the EAP 8 related branches and tags at the
public repo https://github.com/jboss-developer/jboss-eap-quickstarts.

* This quickstart's `configure-security-domain.cli` script will also need to be updated because it tries to add
an `application-security-domain` mapping in the Undertow subsystem that already exists in the out of the box configuration.
* Some dependency updates will also be needed since running `mvn clean install` from `custom-module` results in build failures
due to missing dependency versions (the `custom-module/pom.xml` isn't using the BOM to get the versions).

=== Nice-to-Have Requirements

=== Non-Requirements

* The QS is not intended for managed domain
* The QS is not supported on OpenShift.

== Backwards Compatibility

// Does this enhancement affect backwards compatibility with previously released
// versions of WildFly?
// Can the identified incompatibility be avoided?

=== Default Configuration

=== Importing Existing Configuration

=== Deployments

=== Interoperability

//== Implementation Plan
////
Delete if not needed. The intent is if you have a complex feature which can 
not be delivered all in one go to suggest the strategy. If your feature falls 
into this category, please mention the Release Coordinators on the pull 
request so they are aware.
////

== Security Considerations

////
Identification if any security implications that may need to be considered with this feature
or a confirmation that there are no security implications to consider.
////

== Test Plan

On the engineering side, manual verification will be done by following
the steps from the quickstart README.

== Community Documentation

The quickstart and its documentation is already in the community.

== Release Note Content
////
Draft verbiage for up to a few sentences on the feature for inclusion in the
Release Note blog article for the release that first includes this feature. 
Example article: http://wildfly.org/news/2018/08/30/WildFly14-Final-Released/.
This content will be edited, so there is no need to make it perfect or discuss
what release it appears in.  "See Overview" is acceptable if the overview is
suitable. For simple features best covered as an item in a bullet-point list 
of features containing a few words on each, use "Bullet point: <The few words>" 
////
A new http-custom-mechanism quickstart that demonstrates how to configure a custom HTTP authentication mechanism
has been added to the EAP quickstarts.
