= Add OpenTelemetry to the EAP XP quickstarts
:author:            Jason Lee
:email:             jasondlee@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

EAP XP 5 adds support for OpenTelemetry, but there is no demonstration on how to use this new support. This QS will add a basic example showing how to enable support in XP and how an application might make use of it.

== Issue Metadata

=== Issue

* https://issues.redhat.com/browse/EAP7-1799[EAP7-1799]
* https://issues.redhat.com/browse/WFLY-15849[WFLY-15849]

=== Related Issues


=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

=== Testing By
// Put an x in the relevant field to indicate if testing will be done by Engineering or QE. 
// Discuss with QE during the Kickoff state to decide this
* [ ] Engineering

* [ ] QE

=== Affected Projects or Components

=== Other Interested Projects

=== Relevant Installation Types
// Remove the x next to the relevant field if the feature in question is not relevant
// to that kind of WildFly installation
* [x] Traditional standalone server (unzipped or provisioned by Galleon)

* [x] Managed domain

* [x] OpenShift s2i

* [x] Bootable jar

== Requirements

=== Hard Requirements

* A new quickstart will be adding showing:
** How to enable OpenTelemetry support
** How to consume OpenTelemetry in an application
** How to stand up a simple Jaeger instance to capture the telemetry data

=== Nice-to-Have Requirements

=== Non-Requirements

== Backwards Compatibility

This is a new QS

=== Default Configuration

=== Importing Existing Configuration

=== Deployments

=== Interoperability

//== Implementation Plan
////
Delete if not needed. The intent is if you have a complex feature which can 
not be delivered all in one go to suggest the strategy. If your feature falls 
into this category, please mention the Release Coordinators on the pull 
request so they are aware.
////

== Security Considerations

////
Identification if any security implications that may need to be considered with this feature
or a confirmation that there are no security implications to consider.
////

== Test Plan

On the engineering side, manual verification will be done by following
the steps from the quickstart README. Additionally, the quickstart includes an Arquillian-based test verifying functionality.

== Community Documentation

The quickstart and its documentation is already in the community.

== Release Note Content
////
Draft verbiage for up to a few sentences on the feature for inclusion in the
Release Note blog article for the release that first includes this feature. 
Example article: http://wildfly.org/news/2018/08/30/WildFly14-Final-Released/.
This content will be edited, so there is no need to make it perfect or discuss
what release it appears in.  "See Overview" is acceptable if the overview is
suitable. For simple features best covered as an item in a bullet-point list 
of features containing a few words on each, use "Bullet point: <The few words>" 
////
A new opentelemetry-tracing quickstart that demonstrates how to integrate OpenTelemetry into
an application, as well as a simple setup of the OpenTelemetry Collector to receive and
aggregate the tracing signals
