---
# Add any category for this proposal as a yaml list, e.g.
# - core
# - management
# if missing, add it to _data/wildfly-categories and use its id
categories:
- observability
# Specify the stability level of the feature.
# Values can be one of: experimental preview community default
stability-level: default
# Specify the Feature Development tracker issue for the feature.
# This must be an issue tracked in https://github.com/orgs/wildfly/projects/7/views/1.
# To create a Feature Development tracker issue, go to  https://github.com/wildfly/wildfly-proposals/issues/new/choose
# and select 'Feature Development'
issue: https://github.com/wildfly/wildfly-proposals/issues/715
# Provide the github ids of the members of the feature team, organized by role.
# Provide a single id for the 'assignee' role. Use a yaml list for the 'sme' and
# 'outside-perspective' roles, even if there is only one person in a role.
feature-team:
 developer: jasondlee
 sme:
  -
 outside-perspective:
  -
# If this issue tracks the promotion to a higher stability level of a previously
# completed feature, provide the URL of the https://github.com/wildfly/wildfly-proposals/issues
# issue that was used to track the previous feature.
promotes: https://github.com/wildfly/wildfly-proposals/issues/590
# This should be blank during initial development of a feature. It may be used
# after the feature is completed if a subsequent issue is field to track promotion
# of this feature to a higher stability level
promoted-by:
---

= WFLY-20560 - Promote Micrometer Prometheus to `DEFAULT` stability
:author:            Jason Lee
:email:             jasondlee@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

////
__<The entire document should be one to two pages long. We will write each analysis document as if it is a conversation with a future developer. This requires a good writing style, with full sentences organized into paragraphs. Bullets are acceptable only for visual style, not as an excuse for writing sentence fragments.>__
////

== Overview
////
__<Define the requirement here. Be clear and succinct, you should be able to clearly define the context or problem in two or three paragraphs (if not sentences). Try to define the problem in the overall context and not to get into too much technical detail at this point.>__
////

Micrometer Prometheus shipped with WildFly 36. To meet downstream roadmap requirements, this feature needs to be promoted to `Stability.DEFAULT` to allow its inclusion there.

=== User Stories

////
__<Provide one or more brief user stories that illustrate the intended users of the feature and the goal they will seek to achieve by using the feature.>__
////

- As a server administrator, I would like to be able to use existing Kubernetes monitoring tools to capture and analyze Prometheus metrics so that I may monitor application and server health.

== Issue Metadata

* https://issues.redhat.com/browse/WFLY-20560[]
* https://issues.redhat.com/browse/EAP7-2308[]

=== Related Issues

////
__<List the issues related to this feature>__
////

* https://issues.redhat.com/browse/WFLY-18582[WFLY-18582]
* https://issues.redhat.com/browse/EAP7-2234[EAP7-2234]
* https://issues.redhat.com/browse/EAP7-2235[EAP7-2235]

=== Affected Projects or Components

////
__<List the projects or components that are affected by the feature. List them using their Git repositories.>__
////

* Micrometer

=== Other Interested Projects

* Downstream/external communities such as OpenShift

=== Relevant Installation Types

////
__<List the installation types that are relevant for the features and remove any that are not relevant>__.
////

* [x] Traditional standalone server (unzipped or provisioned by Galleon)
* [ ] Managed domain
* [x] OpenShift Source-to-Image (S2I)
* [x] Bootable jar

== Requirements

////
__<Describe the requirements that must be fulfilled by this feature.>__

__<For analyses of a promotion of an existing feature to 'preview' or 'community' stability, only list new requirements; existing
 requirements from the feature being promoted are assumed to continue unless otherwise noted in the 'Changed requirements' section. Other analyses, including those for promotion to the 'default' stability level, must list all requirements.>__
////

* All relevant server artifacts/APIs (e.g., models, services, etc.) must be promoted to `DEFAULT`

=== Changed requirements

////
__<Only relevant for analyses of a promotion of an existing feature to
 'preview' or 'community stability. Other analyses should remove this section.>__
////

////
__<For any existing requirements from the feature being promoted that are
 being changed or removed, describe the change.>__
////

This is a stability level promotion only, so no new features will be added.

=== Non-Requirements

////
__<Use this section to explicitly discuss things that readers might think are required but which are not required.>__
////

N/A

=== Future Work

////
__<Use this section to discuss requirements that are not addressed by this proposal but which may be addressed in later proposals.>__
////

As a stability level promotion, the work will be completed in a single effort.

== Backwards Compatibility

////
__<Does this enhancement affect backwards compatibility with previously released versions of WildFly? Can the identified incompatibility be avoided?>__
////

There are no backwards-compatability concerns.

=== Default Configuration

////
__<Does the proposed work change the default value of any current configuration attributes? Does it change the configuration generated by any current Galleon layers?>__
////

Default configurations will be unaffected.

=== Importing Existing Configuration

////
__<Does the proposed work affect the ability to run WildFly running an existing configuration? Is there anything else about the proposed work that may require changes to the WildFly server migration tool?>__
////

Existing configurations will continue to run. All model changes and the code required to migrate to them have already shipped
in WildFly. As this change affects only the stability level, those changes will continue to be relevant and effective here.

=== Deployments

////
__<Does this feature change the behavior of deployments in incompatible ways? If yes please detail what is the deployment issue observed when no change is done, and what is the change needed to solve the deployment issue>__
////

Deployments will be unaffected by this change.

=== Interoperability

////
__<Is this feature impacting interoperability?>__
////
No interoperability concerns.

== Implementation Plan

////
__<This section is optional. If you have a complex feature which can not be delivered all in one go, suggest the strategy.>__
////

Nothing special to note.

== Admin Clients

////
__<Identify the level of compatibility this feature will have with the existing admin clients (JBoss CLI and the Admin Console / HAL). Identify any follow up work that will be required in the clients and link issues created to track this work.>__
////

N/A

== Security Considerations

////
__<What impact on security does this feature have?>__
////

No additional concerns beyond those expressed in xref:WFLY-18582_add-prometheus-endpoint-to-micrometer-extension.adoc[WFLY-18582]

[[test_plan]]
== Test Plan

////
__<Depending on the selected stability level, the appropriate section below should be completed, including a brief description of how testing is to be performed in accordance with the selected stability level. The non-relevant sections may be removed as needed.>__
////

////
Depending on the stability level, the test plan required may vary. see below:
////

The feature is already tested at `COMMUNITY`, but the coverage will be analyzed by Red Hat QE and this section updated as needed.

== Community Documentation

////
__<Describe how this feature will be documented or illustrated. Generally a feature should have documentation as part of the PR to wildfly main, or as a follow up PR if the feature is in wildfly-core. In some cases though the feature will bring additional content (such as quickstarts, guides, etc.). Indicate which of these will happen>__
////

No additional documentation will be needed.

== Release Note Content

////
__<Draft verbiage for up to a few sentences on the feature for inclusion in the Release Note blog article for the release that first includes this feature.__
__Example article: https://www.wildfly.org/news/2024/01/25/WildFly31-Released/.__
__This content will be edited, so there is no need to make it perfect or discuss what release it appears in.>__
////

"The Micrometer Prometheus feature has been promoted from the `COMMUNITY` stability level to `DEFAULT`."
