= Title
:author:            David Lloyd
:email:             david.lloyd@redhat.com
:toc:               left
:icons:             font
:keywords:          deployment
:idprefix:
:idseparator:       -

== Overview

We need to move to child-first class and resource resolution in deployments.
The first step must be validation of deployment contents and dependencies.
This entails detecting deployment artifacts which have packages or resources which conflict with container packages or resources.

Once this proposal is implemented, we can move to changing dependency order, which will come in a follow-up proposal.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFCORE-3522[WFCORE-3522]

=== Related Issues

* https://issues.jboss.org/browse/SWARM-1691[SWARM-1691]
* https://issues.jboss.org/browse/WFLY-9828[WFLY-9828]

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:mjurc@redhat.com[Michal Jurc]

=== Affected Projects or Components

* WildFly Core
* All deployment-related subsystems

=== Other Interested Projects

== Requirements

=== Hard Requirements

* The deployer must provide a way for subsystems to register packages and resources that are indicative of invalid deployment content.
This likely entails introducing a multi-valued capability which is consumed by the deployment system.
** The deployer must correlate this information in such a way that if the subsystem is disabled for a given deployment via ``exclude-subsystem`` in ``jboss-deployment-structure.xml``, the deployment can proceed without error.
** There may be APIs that must always be forbidden, even when the ``exclude-subsystem`` flag is set.
In these cases, the subsystem must have a way to indicate this situation.
* The deployer must ignore invalid content.
* The deployer must produce clear, user-friendly warnings about invalid content, ideally with a suggested remedy.

=== Nice-to-Have Requirements

* Implement an optional deployment mode where users could specify that they wish to reject deployments with invalid content.
This could become the default setting in some future version.
* Implement a feature where duplicated classes between deployment archives are logged as warnings.
** For example, ``aa.jar and bb.jar contain 294 conflicting or duplicated classes in 25 packages, which may result in class loading problems``
** It may be necessary to iterate N×M archives to print the comprehensive report
** List individual packages at DEBUG, classes at TRACE
* Perhaps implement a "second level" of verification for packages which "benignly" conflict
** An example would be, a deployment includes a Java EE API but the corresponding subsystem was disabled for the deployment

=== Non-Requirements

== Test Plan

* Introduce test cases which include various kinds of invalid content and verify
that the content is ignored.
