= WFLY-12223 Configuring remote-cache-container datagrid nodes based on WildFly Discovery SPI
:author:            Radoslav Husar
:email:             rhusar@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

The configuration of known data grid servers in the Infinispan subsystem is currently static.
It consists of any number of named server groups, each group is a list of references to outbound-socket-bindings.
Such configuration is thus completely static.
This can be generalized with WildFly Discovery SPI.
The general facility allows for any other form of discovery, e.g. general cloud-specific discovery.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFLY-12223[WFLY-12223 Configuring remote-cache-container datagrid nodes based on WildFly Discovery SPI]
* https://issues.jboss.org/browse/EAP7-1326[EAP7-1326 Infinispan subsystem integration with WildFly Discovery SPI]

=== Related Issues

* https://issues.jboss.org/browse/WFLY-12222[WFLY-12222 Clustering subsystems integration with WildFly Discovery SPI (tracker Jira)]
* https://issues.jboss.org/browse/EAP7-1249[EAP7-1249 Clustering subsystems integration with WildFly Discovery SPI (tracker Jira)]

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:tborgato@redhat.com[Tommasso Borgato]

=== Testing By

[ ] Engineering

[x] QE

=== Affected Projects or Components

* Infinispan; but no changes should be required in projects.

=== Other Interested Projects

* N/A

== Requirements

=== Hard Requirements

* remote-cache-container in Infinispan subsystem can reference discovery provider to be queried
* The initial implementation, this can only be used with static list, which is currently implemented in the WildFly Discovery project
* Each server group only ever references a single discovery provider - if multiple providers are to be used, the aggregation facility of the discovery subsystem is used.
* Capability is in place to enforce model referential integrity.

=== Nice-to-Have Requirements

* N/A

=== Non-Requirements

* N/A

//== Implementation Plan
////
Delete if not needed. The intent is if you have a complex feature which can
not be delivered all in one go to suggest the strategy. If your feature falls
into this category, please mention the Release Coordinators on the pull
request so they are aware.
////
== Test Plan

* Limited coverage might be added to WildFly's integration test suite.
* QE will provide a test plan.

== Community Documentation

This will be documented in WildFly's Infinispan section in High-Availability guide since this is WildFly specific.
