---
categories:
  - clustering
---
= Remote cache metrics
:author:            Paul Ferraro
:email:             paul.ferraro@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

Infinispan 9.x added statistics collections for HotRod clients to caches hosted on remote Infinispan servers.
The original remote cache integration was written for Infinispan 8.2.x, before this existed.
The goal of this feature request is to expose remote cache statistics to the management model as runtime metrics, the collection of which should be enabled/disabled by a management attribute.

== Issue Metadata

=== Issue

* https://issues.redhat.com/browse/WFLY-12165

=== Related Issues

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:tborgato@redhat.com[Tommaso Borgato]

=== Testing By
// Put an x in the relevant field to indicate if testing will be done by Engineering or QE. 
// Discuss with QE during the Kickoff state to decide this
[X] Engineering

[ ] QE

=== Affected Projects or Components

Clustering

=== Other Interested Projects

== Requirements

=== Hard Requirements

* Add boolean statistics-enabled attribute per remote-cache-container that enables/disables the collection of statistics.
* Expose https://docs.jboss.org/infinispan/9.4/apidocs/org/infinispan/client/hotrod/jmx/RemoteCacheManagerMXBean.html[connection-related runtime metrics] for each remote-cache-container:
* Expose runtime resources per started RemoteCache
** For each remote cache runtime resource, expose https://docs.jboss.org/infinispan/9.4/apidocs/org/infinispan/client/hotrod/jmx/RemoteCacheClientStatisticsMXBean.html[all runtime metrics].
** Expose management operation for resetting statistics.
* Add transformer that discards the new enable statistics attribute for older model versions.

=== Nice-to-Have Requirements

* When statistics are enabled, enable JMX mbean registration if mbean server is available
* Register management operations for switching a HotRod client from one cluster to another.
** This is used to support manual failback in the event of a site failover when infinispan servers are configured with cross-site replication

=== Non-Requirements

== Test Plan

* Enhance existing hotrod-based session manager tests to validate the existence of runtime resource for the deployment specific remote cache and sanity checks for a selection of metrics.

== Community Documentation

* Enhance Infinispan subsystem documentation to describe how to enable statistics collection for remote caches and where to find the collected statistics, referring to wildscribe for details.
