= Add Setting to Control Global Resources Usage for Messaging Servers
:author:            Jeff Mesnil
:email:             jmesnil@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFLY-10326[WFLY-10326]

=== Related Issues

* https://issues.jboss.org/browse/EAP7-830[EAP7-830]
* https://issues.apache.org/jira/browse/ARTEMIS-581[ARTEMIS-581]

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:mnovak@redhat.com[Miroslav Novak]

=== Affected Projects or Components

* Artemis has been providing the underlying feature since 1.4.0. It does not require a component upgrade.

=== Other Interested Projects

== Requirements

* Add a `global-max-memory-size` attribute to the https://wildscribe.github.io/WildFly/12.0//subsystem/messaging-activemq/server/[/subsystem=messaging-activemq/server resource] to control the maximum
amount of memory that Artemis can use to store messages for its addresses before they are considered "full" and
their `address-full-policy` starts to apply (e.g. to drop messages, block producers, etc.). Default is `undefined` (meaning that there is no limit).
+
This attribute is in addition to the individual memory setting applied to each Artemis address through the
use of the `max-size-bytes` attribute of the https://wildscribe.github.io/WildFly/12.0/subsystem/messaging-activemq/server/address-setting/[address-setting resource]

* Add a `global-max-disk-size`  attribute to the https://wildscribe.github.io/WildFly/12.0//subsystem/messaging-activemq/server/[/subsystem=messaging-activemq/server resource] to control the maximum
space Artemis can use to store data on the file system. Once that limit is reached,  any message will be blocked. This attribute is expressed in percentage of the available space on the disk (min 0, max 100).
The default value is `undefined` (meaning that there is no limit).

=== Hard Requirements

N/A

=== Nice-to-Have Requirements

N/A

=== Non-Requirements

N/A

== Test Plan

* Standard subsystem & transformer tests for legacy version will be added to the subsystem test suite
* The memory feature will be tested in the QE test suite to ensure that once Artemis has filled its
addresses in memory for the amount specified by the `global-max-memory-size` attribute, the `address-full-policy` will take effect.
* Likewise, the disk feature will be tested in the QE test suite to ensure that once Artemis has filled the disk
up to the percentage set by `global-max-disk-size`, it will block any message processing.

== Community Documentation

The feature will be documented in WildFly Admin Guide (in the Messaging Configuration section).
