---
categories:
  - messaging
stability-level: default
issue: https://github.com/wildfly/wildfly-proposals/issues/709

feature-team:
 developer: ehsavoie
 sme:
  -
 outside-perspective:
  -
---

= Expose Artemis commit-interval attribute for scaledown
:author:            Emmanuel Hugonnet
:email:             ehugonne@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

When moving messages from the server scaling down, all the operation is done in a single transaction which means that all the messages need to be in memory and can lead to a OOME. The purpose of this feature is to enable the size of the transaction (aka the number of messages) to be defined so that messages are moved by blocks instead of a single block.

=== User Stories

As an administrator I want to be able to scale down a node in my cluster when the load is decreasing and configuring the number of messages to be moved  in a batch.

== Issue Metadata

=== Related Issues
 * https://issues.redhat.com/browse/EAP7-2296[EAP7-2296]
 * https://issues.redhat.com/browse/JBEAP-28739[JBEAP-28739]
 * https://issues.redhat.com/browse/WFLY-19752[WFLY-19752]
 * https://issues.apache.org/jira/browse/ARTEMIS-5053[ARTEMIS-5053]
 

=== Affected Projects or Components

* https://github.com/apache/activemq-artemis/[Apache Artemis]
* WildFly

=== Other Interested Projects

=== Relevant Installation Types

* Traditional standalone server (unzipped or provisioned by Galleon)
* Managed domain
* OpenShift Source-to-Image (S2I)
* Bootable jar

== Requirements

* Add an optional `scale-down-commit-interval` integer to the  https://docs.wildfly.org/35/wildscribe/subsystem/messaging-activemq/server/ha-policy=replication-colocated/configuration=secondary/index.html[/subsystem=messaging-activemq/server/ha-policy=replication-colocated/configuration=secondary] to control the size of the messages transaction block.
* Add an optional `scale-down-commit-interval` integer to the  https://docs.wildfly.org/35/wildscribe/subsystem/messaging-activemq/server/ha-policy=shared-store-colocated/configuration=secondary/index.html[/subsystem=messaging-activemq/server/ha-policy=shared-store-colocated/configuration=secondary] to control the size of the messages transaction block.
* Add an optional `scale-down-commit-interval` integer to the  https://docs.wildfly.org/35/wildscribe/subsystem/messaging-activemq/server/ha-policy=shared-store-secondary/index.html[/subsystem=messaging-activemq/server/ha-policy=shared-store-secondary] to control the size of the messages transaction block.
* Add an optional `scale-down-commit-interval` integer to the  https://docs.wildfly.org/35/wildscribe/subsystem/messaging-activemq/server/ha-policy/live-only/index.html[/subsystem=messaging-activemq/server/ha-policy=shared-store-secondary] to control the size of the messages transaction block.

Those attributes should have a default value of "-1" and any negative value should be converted to that.

=== Changed requirements

N/A

=== Non-Requirements

N/A

=== Future Work

N/A

== Backwards Compatibility

N/A

=== Default Configuration

N/A

=== Importing Existing Configuration

N/A

=== Deployments

N/A

=== Interoperability

N/A

== Implementation Plan

Add a new integer attribute `scale-down-commit-interval` with no default value to the ScaleDown attributes, then update the schema accordingly and register a model transformer.

== Admin Clients

N/A

== Security Considerations

N/A

[[test_plan]]
== Test Plan

__<Depending on the selected stability level, the appropriate section below should be completed, including a brief description of how testing is to be performed in accordance with the selected stability level. The non-relevant sections may be removed as needed.>__
////
Depending on the stability level, the test plan required may vary. see below:
////

** Experimental - No test plan is required. Basic unit / integration tests should be added during development.

** Preview - a brief high-level description of the testing approach should be added here, including types of tests added (unit, integration, smoke, component, subsystem, etc.) Note that not all test types are required for a particular feature, so include a description of what is being tested and the approach chosen to perform the testing.

** Community - this level should include everything in the 'Preview' stability level, plus the following additional testing as relevant:
*** Manual tests: briefly describe checks to be performed during one-time exploratory testing. The purpose of this testing is to check corner cases and other cases that are not worth implementing as automated tests. Typical checks are: bad configurations are easy to reveal, attribute descriptions and error messages are clear, names are descriptive and consistent with similar resources, default values are reasonable.
    If there is an existing quickstart affected by the feature, manual checks include following the quickstart's guide and verifying functionality.
*** Miscellaneous checks: Manual checks for significant changes in server performance, memory and disk footprint should be described here. These checks are not always relevant, but consideration of these impacts, and others, are strongly encouraged and should be described here. Fully qualified test case names should be provided along with a brief description of what the test is doing.
*** Integration tests - at the 'Community' stability level, complete integration tests should be provided.
*** Compatibility tests - if backwards compatibility is relevant to the feature, then describe how the testing is performed.

** Default - This stability level is reserved and requires approval by a professional Quality Engineer with subject matter expertise.

== Community Documentation

__<Describe how this feature will be documented or illustrated. Generally a feature should have documentation as part of the PR to wildfly main, or as a follow up PR if the feature is in wildfly-core. In some cases though the feature will bring additional content (such as quickstarts, guides, etc.). Indicate which of these will happen>__

== Release Note Content

__<Draft verbiage for up to a few sentences on the feature for inclusion in the Release Note blog article for the release that first includes this feature.__
__Example article: https://www.wildfly.org/news/2024/01/25/WildFly31-Released/.__
__This content will be edited, so there is no need to make it perfect or discuss what release it appears in.>__ 
