---
categories:
  - ee
---
=  [Preview] Standard WildFly support for Jakarta MVC 2.1
:author:            Brian Stansberry
:email:             brian.stansberry@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

https://jakarta.ee/specifications/mvc/[Jakarta MVC] is a Jakarta specification project for
providing support for the Model-View-Controller pattern in web applications. The specification
has had three releases, and a fourth is in the works. It has been considered for incorporation
in the Jakarta EE Platform or Web Profile, although it was not included in Jakarta EE 11.

The intent here is to provide preview support for Jakarta MVC in standard WildFly. Previously we https://issues.redhat.com/browse/WFLY-18838[introduced Jakarta MVC support in WildFly Preview]. This proposal is to bring preview stability level support to standard WildFly.


== Issue Metadata

=== Issue

* https://issues.redhat.com/browse/WFLY-19062[WFLY-19062]

=== Related Issues

* https://issues.redhat.com/browse/WFLY-18838[WFLY-18838]
* https://issues.redhat.com/browse/WFLY-19021[WFLY-19021]

=== Stability Level
// Choose the planned stability level for the proposed functionality
* [ ] Experimental

* [X] Preview

* [ ] Community

* [ ] default

=== Dev Contacts

* mailto:brian.stansberry@redhat.com[Brian Stansberry]

=== QE Contacts

=== Testing By
// Put an x in the relevant field to indicate if testing will be done by Engineering or QE. 
// Discuss with QE during the Kickoff state to decide this
* [X] Engineering

* [ ] QE

=== Affected Projects or Components

* mvc-krazo-feature-pack

=== Other Interested Projects

=== Relevant Installation Types
// Remove the x next to the relevant field if the feature in question is not relevant
// to that kind of WildFly installation
* [x] Traditional standalone server (unzipped or provisioned by Galleon)

* [x] Managed domain

* [x] OpenShift s2i

* [x] Bootable jar

== Requirements

=== Hard Requirements

* Provide an extension/subsystem that makes modules containing the Jakarta MVC 2.1 api 
  and the Eclipse Krazo implementation available to an application.
** Only the Jakarta MVC API module will be jboss-api=public; other modules added here will be jboss-api=private
* Provide an 'mvc-krazo' Galleon layer
** The layer will depend on the 'bean-validation', 'cdi', 'jaxrs-core' and 'jsf' layers, in line
   with Jakarta MVC's dependencies on other EE specifications.
* Provide an extension/subsystem artifact jar, and a 'galleon-shared' src zip for use
  in other feature packs.
* Incorporate the above in the 'wildfly' and 'wildfly-preview' feature packs.
* Extension will advertise itself as having stability level 'preview'.
* JBoss Modules modules associated with the feature will not be provisioned if the user has disabled provisioning of 'preview' stability features.

=== Nice-to-Have Requirements
// Requirements in this section do not have to be met to merge the proposed functionality.
// Note: Nice-to-have requirements that don't end up being implemented as part of
// the work covered by this proposal should be moved to the 'Future Work' section.


=== Non-Requirements
// Use this section to explicitly discuss things that readers might think are required
// but which are not required.
 * Inclusion of the extension/subsystem in any standard OOTB config, including docs/examples configs.
 * Inclusion in any of the WildFly user boms.
 * Quickstart.

=== Future Work
// Use this section to discuss requirements that are not addressed by this proposal
// but which may be addressed in later proposals.
* Subsequent promotion to 'community' stability.
* Possible move into the 'wildfly-ee' feature pack.
** This would reflect a 'promotion' in terms of WildFly's long term compatibility expectations for Jakarta MVC itself.
* Add a quickstart
** Requires promotion to 'community' or Quickstart project support for preview features.

== Backwards Compatibility

// Does this enhancement affect backwards compatibility with previously released
// versions of WildFly?
// Can the identified incompatibility be avoided?

=== Default Configuration

No incompatibility.

=== Importing Existing Configuration

No incompatibility.

=== Deployments

No incompatibility.

=== Interoperability

No incompatibility.

//== Implementation Plan
////
Delete if not needed. The intent is if you have a complex feature which can 
not be delivered all in one go to suggest the strategy. If your feature falls 
into this category, please mention the Release Coordinators on the pull 
request so they are aware.
////
Use WildFly Extras to house the source code. Incorporate into the 'wildfly' and 'wildfly-preview' feature packs in a manner similar to how we incorporate content from WildFly Core into the 'wildfly-ee' feature pack.

== Security Considerations

////
Identification if any security implications that may need to be considered with this feature
or a confirmation that there are no security implications to consider.
////
None.

== Test Plan

 * Standard subsystem tests (parsing and marshalling; Stage.MODEL execution)
 ** Done in the mvc-krazo-feature-pack project.
 * Pass the Jakarta MVC TCK
 ** TCK runner should support passing in the GAV of the feature pack to provision the 
    server, allowing execution against both the wildfly-preview feature pack and
	the mvc-krazo-specific feature pack
 * Smoke test in the testsuite/integration/manualmode module
 ** In the future to be moved to testsuite/integration/basic (perhaps for WildFly 32)
 * Smoke test in the testsuite/preview/basic module (covering testing an installation that provisions the subsystem via the mvc-krazo layer)
 * Test the layer by itself and as part of the all-layers provisioning in testsuite/layers-expansion/LayersTestCase

== Community Documentation

 * Addition of a 'Jakarta MVC' subsection in the 'Subsystem configuration' section of the Admin Guide.
 * Updated project README explaining this is now included in standard WildFly.
 * Removal of the mention in the 'WildFly and WildFly Preview' document as a difference between the two.
 * Updated mention in the https://docs.wildfly.org/30/Admin_Guide#Simple_configuration_subsystems[Simple configuration subsystems section of the Admin Guide] to reflect this is not solely WildFly Preview.
 * Update to the specification section in the https://docs.wildfly.org/30/Getting_Started_Guide.html[Getting Started Guide] to reflect this is not solely a WildFly Preview feature.

== Release Note Content

WildFly now provides preview stability support for Jakarta MVC, using the Eclipse Krazo implementation. This is available in standard WildFly and in WildFly Preview. 
To use the subsystem in standard WildFly the server must be started with the `--stability=preview` parameter.
