= Support simplified configuration of the Graceful Timeout and Shutdown Timeout in service scripts
:author:            Yeray Borges
:email:             yborgess@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview

The server can be installed as a Linux service by using two types of init daemon services:

* Init, also known as System V init, or SysVinit: The server is shipped with the required files to install it as an Init daemon service at $SERVER_HOME/docs/contrib/scripts/init.d
* Systemd (System daemon): The server is shipped with the required files to install it as a System daemon service at $SERVER_HOME/docs/contrib/scripts/systemd

When the server is installed as a service, two parameters can be used to control how the server behaves when it is stopped or restarted:

* Graceful Shutdown Timeout: This timeout configures how long the server will be suspended before initiating the real shutdown of the subsystems. This setting is useful to give the subsystems enough time to finish any inflight operations before the server can be shut down. For example, to allow the transaction subsystem to finish any running transactions. This timeout can be used by enabling the following system property when the server starts: `-Dorg.wildfly.sigterm.suspend.timeout=<timeout>`.

* Shutdown Timeout: This timeout controls how long the whole shutdown process takes, including the time used by the subsystems to complete the graceful shutdown. It sends the SIGKILL signal to the server process to kill it when the time is up. You can configure it on:
** Init daemon services: The user can configure it on $SERVER_HOME/docs/contrib/scripts/init.d/wildfly.conf by using the SHUTDOWN_WAIT environment variable.
** Systemd services: The user can configure it on $SERVER_HOME/docs/contrib/scripts/systemd/wildfly.service by using the `TimeoutStopSec` directive.

The Shutdown Timeout always wins, if the graceful shutdown timeout is bigger than the shutdown timeout, you could be in the situation where your server is killed in the middle of a suspension.

The initial goal of this RFE was to standardize the configuration of both timeouts on both types of scripts by using environment variables. However, that's not possible for the `TimeoutStopSec` directive, because systemd directives don't allow variable expansions. To accomplish the goal for this directive we would need to stop the server by supplying a new bash script to be executed on the `ExecStop` directive. It is better to use the out-of-the-box directive instead of reimplementing a similar feature by us. In addition, systemd services only would accept command line variables when these variables are configured as global variables. Those global variables are made available to all the systemd services, so changes could affect to any other service installation or have side effects out of its purpose.

The goal of this RFE is to make available the configuration of the Graceful Shutdown Timeout by using a more simple variable that can be configured by the user instead of `-Dorg.wildfly.sigterm.suspend.timeout=<timeout>`.

== Issue Metadata

=== Issue

* https://issues.redhat.com/browse/WFCORE-5689[WFCORE-5689]

=== Related Issues

* https://issues.redhat.com/browse/EAP7-1857[EAP7-1857]

=== Dev Contacts

* mailto:yyang@redhat.com[Yong Yang]
* mailto:{email}[{author}]

=== QE Contacts

=== Testing By
// Put an x in the relevant field to indicate if testing will be done by Engineering or QE.
// Discuss with QE during the Kickoff state to decide this
* [ ] Engineering

* [X] QE

=== Affected Projects or Components

* init.d scripts
* systemd scripts

=== Other Interested Projects

=== Relevant Installation Types
// Remove the x next to the relevant field if the feature in question is not relevant
// to that kind of WildFly installation
* [x] Traditional standalone server (unzipped or provisioned by Galleon)

* [x] Managed domain

* [ ] OpenShift s2i

* [ ] Bootable jar

== Requirements

=== Hard Requirements

* Add a new environment variable named GRACEFUL_SHUTDOWN_TIMEOUT and make it available for configuration on the Init daemon and System daemon scripts used for the server.

=== Nice-to-Have Requirements

=== Non-Requirements

* Configure the Graceful shutdown timeout and shutdown timeout by using the environment from the command line.

== Backwards Compatibility

N/A

=== Default Configuration

N/A

=== Importing Existing Configuration

N/A

=== Deployments

N/A

=== Interoperability

N/A

== Security Considerations

N/A

== Test Plan

* Manual configuration of the server by using Init and system daemon scripts. Configure it with different values for the Graceful Shutdown Timeout and Shutdown Timeout and verify they work as expected.

== Community Documentation

* The new environment variable will be documented on the service configuration file. We can also add there a note about how to modify the Shutdown Timeout by using the `TimeoutStopSec` directive.

== Release Note Content

* Bullet point: Added GRACEFUL_SHUTDOWN_TIMEOUT variable to configure the graceful shutdown timeout when the server is launched as a service.

