---
categories:
- client
- ejb
- jndi
- transactions
stability-level: community
issue: 737
feature-team:
 developer: ropalka
 sme:
 - fl4via
 - rachmatowicz
 outside-perspective:
  - tadamski
---

= Support client-side and server-side handler versioning for EJB/HTTP, Naming/HTTP and Transactions/HTTP
:author:            Richard Achmatowicz
:email:             rachmato@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:

== Overview

The purpose of this Request For Enhancement (RFE) is to provide a versioning mechanism for client-side and server-side handlers
for the Wilfly client libraries when using HTTP as a transport protocol. In this context, a client-side handler has responsibilities
for creating the HTTP request message sent to the server, as well as processing the HTTP response message received back from the server.
Similarly, a server-side handler is responsible for receiving the HTTP request message from the client and sending the HTTP response
message back to the client.

Handler versioning is required in order to add changes to the HTTP request and response messages, as well as adding functionality
related to the processing of those messages. For example, in order to support affinity management of EJB/HTTP requests, request routing
data (cookies) need to be added to requests, and those cookies need to be processed on the client side as well as the server side.

Handler versioning is also required to maintain backward compatibility: newer versions of handlers may involve functionality not
available to handlers in earlier versions.

To get agreement on which handlers should be used, a handshake protocol between client and server will need to negotiate which handler
version to use, generally the maximum version common to both client and server.

=== User Stories

This feature does not have associated user stories, as the functionality provided is auto-managed by the client library itself, with
no required input from the user.

== Issue Metadata

=== Related Issues

* EAP7-2298: the EAP7 RFE to which this analysis document belongs
* WFLY-20532: integration of the featrure into Wildfly
* WEJBHTTP-153: principal coding changes of the feature in the client libraries
* Feature Planning Project Issue #56: for feature planning in Wildfly (see https://github.com/orgs/wildfly/projects/7/views/1)

=== Affected Projects or Components

Use of the Wildfly client libraries is affected by this feature change.

=== Other Interested Projects

=== Relevant Installation Types

* Traditional standalone server (unzipped or provisioned by Galleon)
* Managed domain
* OpenShift Source-to-Image (S2I)
* Bootable jar

== Requirements

This change impacts several aspects of the Wildfly HTTP client.

=== 1. Handler versioning

In order to describe a context for this versioning requirement, we assume that the request response processing that takes
place between a Wildfly HTTP client application and a Wildfly server can be viewed abstractly as consisting of four parts:

* request preparation (client-side)
* request handling (server-side)
* reponse preparation (server-side)
* response handling (client-side)

These are the client-side and server-side handlers which need to be versioned. In this context, the requirements for this
aspect are as follows:

* allow a numeric handler version to be associated with the 4-tuple (request preparation, request processing, response preparation, response processing)
* provide an efficient and maintainable way to incorporate handler changes from one version to another
** e.g. maintain completely separate 4-tuples for each handler version
** e.g. maintain one 4-tuple of handlers, each parameterized by handler version

Such handler versioning permits the addition of new features to request/response processing for the Wildfly HTTP client.

=== 2. Handshaking and Backward compatibility

Once we have versioned handlers, it will happen that clients and servers from different Wildfly versions will have different
handler versions available. In order to preserve compatibility between clients and servers from different Wildfly versions,
we require a handshake protocol between client and server to get agreement on which handler version to use.

Therefore, requirements for this aspect are:

* provide a handshake protocol between client and server to negotiate the handler version to be used, based on the formula
min(client handler version, server handler version)

=== 3. Additional handshake parameters

In addition to getting agreement on the handler version to use, there are other aspects of the Wildfly HTTP client which
may differ between client and server and which are required for backward compatibility:

* Java EE vs Jakarta EE platform - to deal with any package renaming required by the version of the EE platform in use
* marshalling regimen - to support different marshalling regimens
* Jakarta EE version - to deal with any potential differences in Jakarta specs

Each of these aspects will have their own numerical version and the handshake protocol will get agreement for these values
to enhance interoperability and backward compatibility.

NOTE: it would be useful for informational and debuging purooses to provide the handshake values in the logs:

* INFO level: announce the agreed values when there is a client-server version mismatch
* DEBUG level: provide the "before" and "after" values for both the client and server before the handshake starts and after
the handshake completes

=== Future Work

This work is motivated by the need to introduce _affinity management_ into the EJB client library. Affinity management, in
this context, concerns the ability of the client to ensure that requests for stateful EJBs will be directed to the node on
which that stateful bean was created. In other words, the client maintains an association or affinity between the specific
stateful EJB the request targets and the target node which receives the invocation. This is requied for purposes of performance
when stateful EJBs are deployed in a cluster.

In order to introduce such a feature, significant changes to the client-side and server-side handlers is required, thus the
need for client-side and server-side version handling to introduce the feature.

== Backwards Compatibility

NOTE: Backward compatibility is taken to mean new versions of software (and data) being able to work with old versions of
the same software software (and data). Forward comatibility similarly is taken to mean old software (and data) being able
to work with new software (and data).

This enhancement does relate directly to the issue of backward compatability. The incompatibilities which may arise span
various aspects:

* Java EE vs Jakarta EE differences, due to package changes
* client-side and server-side handler differences, due to functional changes
* HTTP request message and response message differences, with respect to headers and body
* marshalling choices (future)

Both backward and forward compatibility is guaranteed by the client and server carrying out a handshake on connection establishment
which determines agreed versions of each of these aspects to be used when processing invocations.

=== Default Configuration

Configuration of the HTTP client is setup by the wildfly-config.xml file. There may be some small changes to the schema.

=== Importing Existing Configuration

THis work does not affect existing server configurations, as the feature does not depend on the way in which the server is
configured.

=== Deployments

This feature should not affect deployments in incompatible ways. Deployments may contain embedded Wildfly HTTP client
applications (e.g. the server-client to server architecture). However, the interaction between server-client and server,
even if using different versions, will be negotiated in the same was as a standalone client with a server.

=== Interoperability

NOTE: Interoperability: the ability of software from different vendors or with different architecrures to exchange information and operate semlessly.

The Wildfly client applications generally (irrespective of the particular transport used - Remoting or HTTP) are affected
by the shift from Java EE to Jakarta EE, as these use different package naming conventions. The common solution to this
problem was to introduce the EE Interoperability Protocol which is a handshake between client and server on conection establishment
which sets an EE Interoperability version:

* version 1: use a special interoperability marshaller which converts package names in the appropriate way
* version 2: use the default marshallers

Version 1 is used when the client and server require package transformation during marshalling. Version 2 is used when they
do not.

The EE version is one of the aspects varying between client and server and is handled by the handshake protocol mentioned
earlier.

== Admin Clients

These changes do not affect compatibility with Wildfly CLI or HAL/Admin Colsole.

== Security Considerations

These changes do not impact the security configuration of the Wildfly HTTP client.

[[test_plan]]
== Test Plan

This issue is at stability level "community" and the following required sections apply:

=== Test Plan Overview

The requirements of this issue which require one or more forms of validation through testing are as follows:

* the handshake between client and server produce the expected agreed values, conditional on the client version
and the server varsion(interoperability, compatability)
* for each agreed handshake variable:
** the EE interoperability aspect functions as expected (i.e. the interopeablity mode is determined)
** the client-server tuple assignment functions as expected (i.e. the functional requirements of the EJB client, Naming
client and Transaction client for that client-server handler version function as expected
** the marshalling regimen functions as expected (i.e. the correct marshalling regimen is used for marshalling)
* at onnection establishment time, there is no interference between the handshake protocol and the establishment of secure
connections

=== Manual Tests

Manual tests do not seem to be required in this case, as there are no relevant tests which cannot be automated.

=== Miscellaneous Checks

Check that any options configred by the wildfly-config.xml and relevant to this RFE are validated.

=== Integration Tests

Project-level integration tests will target components of the Wildfly HTTP client at the project component level - effectively
testing fine-grained requirements for integration of components within the Wildfly HTTP client project itself.

Server-level integration tests will target integration between the Wildfly HTTP client library and the server environment
it interacts with - testing coarse-grained requirements for integration between the Wildfly HTTP client library and the various
subsystems of the server it interacts with, as well as overall combined client-server hahaviour.

==== Project-level integration tests

handshakeProtocolTest: validate the behaviour of the handshake protocol between a client and a mock server.

cientHandlerServerhandlerSmokeTest: test that handlers work when using clients and servers of differing handler versions
are combined (and that the handshake finds an agreed handler version))


==== Server-level integration tests

connectionEstablishmentInterferenceTest: Because the handshake protocol of the Wildfly HTTP client operates during connection
establishment between client and server, there can be an interaction with the establishment of a secure connection, which
is "happening at the same time". For example, HTTP authentication can send back a HTTP 401 message requesting additional security
information via a www-authenticate header, and this should be followed by a new request for the resource with a www-authorization
header. This test aims to validate that there is no interference between the HTTP client handshake protocol and the various
supported security configurations for the client libraries.

clientHandlerSeverHandlerSmokeTest: test that for a given client-handler, server-handler tuple, the functonal requirements
of the EJB, Naming and Transaction client are met

NOTE: because each release of the Wildfly HTTP client will have a default client-server handler version, and that client
server interaction is comprehensively tested with that default version in each project release, we only require smoke testing
of the client-server interactions when versions of client and server do not match and depend on the handshake protocol for
agreement.


=== Compatability Tests

A compatibility testsuite exists for validating agreed handshake values between client and server which covers the possible
version pairings between client and server (old client, new server; new client, old server; new server, new server). This
testsuite can be found at: https://github.com/wildfly/wildfly-client-interoperability[Wildfly Client Interoperability]

NOTE: this test is brittle as it depends on complex Byteman rules to extract the agreed handshake values which are senstive to
refactorings; need to consider making the agreed handshake values accessible through a stable API to simplify testing

== Community Documentation

This feature is not something that the user would need to be aware of - for client and server versions which do not match,
the handshake protocol should establish an agreed version. However, a documentation note on the existence of the handshake
protocol, why it is necessary and what it does would be helpful.

== Release Note Content

Such a release note blog item could describe this feature as enhancing compatibility / interoperability between Wildfly HTTP
client versions and the servers they interact with. Both backward and forward compatibity are supported.