---
categories:
- client
- ejb
- jndi
- transactions
stability-level: community
issue: 737
feature-team:
 developer: ropalka
 sme:
 - fl4via
 - rachmatowicz
 outside-perspective:
  - tadamski
---

= Support client-side and server-side handler versioning for EJB/HTTP, Naming/HTTP and Transactions/HTTP
:author:            Richard Achmatowicz
:email:             rachmato@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:

== Overview

This purpose of this Request For Enhancement (RFE) is to provide a versioning mechanism for client-side and server-side handlers
for the Wilfly client libraries when using HTTP as a transport protocol. In this context, a client-side handler has responsabilities
for creating the HTTP request message snt to the server, as well as propcessing the HTTP response message received from the server.
Similarly, a server-side handler is responsible for receiving the HTTP request message from the client and sending the HTTP response
message to the client.

Handler versioning is required in order to add changes to the HTTP request and response messages, was well as adding functionality
related to the processing of those messages. For example, in order to support affinity manement of EJB/HTTP requests, requst routing
data (cookies) need to me added to requests, and those cookies need to be processed on the client side as well as the server side.

Handler versioning is also required to maintain backward compatability: newer versions of handlers may involve functionality not
available to handlers in earlier versions.

To get agreement on which handlers shoudl be used, a handshake protocol between client and server will need to negotiate which handler
version to use, generally the maximum version common to both client and server.

=== User Stories

This feature does not have associated user stories, as the functionality provided is auto-managed by the client library itself, with
no required input from the user.

== Issue Metadata

=== Related Issues

EAP7-2298: the EAP7 RFE to which this analysis document belongs
WFLY-20532: integration of the featrure into Wildfly
WEJBHTTP-153: principal coding changes of the feature in the client libraries

=== Affected Projects or Components

Use of the Wildfly client libraries is affected by this feature change.

=== Other Interested Projects

=== Relevant Installation Types

__<List the installation types that are relevant for the features and remove any that are not relevant>__.

* Traditional standalone server (unzipped or provisioned by Galleon)
* Managed domain
* OpenShift Source-to-Image (S2I)
* Bootable jar

== Requirements

In order to describe a context for the requirements, we assume thaat the request response processing can be viewed asbtracty
as consisting of four parts:

* request preparation (client-side)
* request handling (server-side)
* reponse preparation (server-side)
* response handling (client-side)

The requirements for this feature are as follows:

* allow a numeric handler version to be associated with the 4-tuple (request preparation, request processing, response preparation, response processing)
* provide a handshake protocol between client and server to negotiate the handler version based on min(client handler version, server handler version)
* provide an efficient and maintainable way to incoporate handlr changes from one ersion to another
** e.g. maintain completely separate 4-tuples for each handler version
** e.g. maintain one 4-tuple of handlers, each parameterized by handler version

=== Changed requirements

__<Only relevant for analyses of a promotion of an existing feature to
 'preview' or 'community stability. Other analyses should remove this section.>__

__<For any existing requirements from the feature being promoted that are
 being changed or removed, describe the change.>__


=== Non-Requirements

__<Use this section to explicitly discuss things that readers might think are required but which are not required.>__ 

=== Future Work

__<Use this section to discuss requirements that are not addressed by this proposal but which may be addressed in later proposals.>__

== Backwards Compatibility

__<Does this enhancement affect backwards compatibility with previously released versions of WildFly? Can the identified incompatibility be avoided?>__

=== Default Configuration

__<Does the proposed work change the default value of any current configuration attributes? Does it change the configuration generated by any current Galleon layers?>__

=== Importing Existing Configuration

__<Does the proposed work affect the ability to run WildFly running an existing configuration? Is there anything else about the proposed work that may require changes to the WildFly server migration tool?>__

=== Deployments

__<Does this feature change the behavior of deployments in incompatible ways? If yes please detail what is the deployment issue observed when no change is done, and what is the change needed to solve the deployment issue>__

=== Interoperability

__<Is this feature impacting interoperability?>__

== Implementation Plan

__<This section is optional. If you have a complex feature which can not be delivered all in one go, suggest the strategy.>__

== Admin Clients

__<Identify the level of compatibility this feature will have with the existing admin clients (JBoss CLI and the Admin Console / HAL). Identify any follow up work that will be required in the clients and link issues created to track this work.>__

== Security Considerations

__<What impact on security does this feature have?>__

[[test_plan]]
== Test Plan

__<Depending on the selected stability level, the appropriate section below should be completed, including a brief description of how testing is to be performed in accordance with the selected stability level. The non-relevant sections may be removed as needed.>__
////
Depending on the stability level, the test plan required may vary. see below:
////

** Experimental - No test plan is required. Basic unit / integration tests should be added during development.

** Preview - a brief high-level description of the testing approach should be added here, including types of tests added (unit, integration, smoke, component, subsystem, etc.) Note that not all test types are required for a particular feature, so include a description of what is being tested and the approach chosen to perform the testing.

** Community - this level should include everything in the 'Preview' stability level, plus the following additional testing as relevant:
*** Manual tests: briefly describe checks to be performed during one-time exploratory testing. The purpose of this testing is to check corner cases and other cases that are not worth implementing as automated tests. Typical checks are: bad configurations are easy to reveal, attribute descriptions and error messages are clear, names are descriptive and consistent with similar resources, default values are reasonable.
    If there is an existing quickstart affected by the feature, manual checks include following the quickstart's guide and verifying functionality.
*** Miscellaneous checks: Manual checks for significant changes in server performance, memory and disk footprint should be described here. These checks are not always relevant, but consideration of these impacts, and others, are strongly encouraged and should be described here. Fully qualified test case names should be provided along with a brief description of what the test is doing.
*** Integration tests - at the 'Community' stability level, complete integration tests should be provided.
*** Compatibility tests - if backwards compatibility is relevant to the feature, then describe how the testing is performed.

** Default - This stability level is reserved and requires approval by a professional Quality Engineer with subject matter expertise.

== Community Documentation

__<Describe how this feature will be documented or illustrated. Generally a feature should have documentation as part of the PR to wildfly main, or as a follow up PR if the feature is in wildfly-core. In some cases though the feature will bring additional content (such as quickstarts, guides, etc.). Indicate which of these will happen>__

== Release Note Content

__<Draft verbiage for up to a few sentences on the feature for inclusion in the Release Note blog article for the release that first includes this feature.__
__Example article: https://www.wildfly.org/news/2024/01/25/WildFly31-Released/.__
__This content will be edited, so there is no need to make it perfect or discuss what release it appears in.>__ 
