---
categories:
  - console
  - logging
---
= Expose named-formatter Attribute on the syslog-handler Resource
:author:            Harald Pehl
:email:             hpehl@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.redhat.com/browse

== Overview

Expose the new `named-formatter` attribute to the `/subsystem=logging/syslog-handler=*` resource.

== Issue Metadata

=== Issue

* {issue-base-url}/HAL-1601[HAL-1601]
* {issue-base-url}/EAP7-1291[EAP7-1291]

=== Related Issues

* {issue-base-url}/WFCORE-4332[WFCORE-4332]
* {issue-base-url}/EAP7-1195[EAP7-1195]

=== Dev Contacts

* mailto:hpehl@redhat.com[Harald Pehl]

=== QE Contacts

* mailto:jkasik@redhat.com[Jan Kasik]

=== Testing By
    
[x] Engineering
    
[ ] QE

=== Affected Projects or Components

* WildFly
* HAL

== Requirements

* Include new `named-formatter` attribute for `/subsystem=logging/syslog-handler=*` resource.

== Test Plan

The test will add a new test case to the test suite which will navigate to the logging configuration application and make sure the attribute is exposaed. The test will also modify the attribute and make sure the changes are persisted in the management model.

== Community Documentation

See the official HAL website at https://hal.github.io
