---
categories:
- console
- microprofile
- observability
stability-level: default
issue: https://github.com/wildfly/wildfly-proposals/issues/788
feature-team:
 developer: hpehl
 sme:
  - jasondlee
 outside-perspective:
  - rhusar
promotes:
promoted-by:
---
= Support Micrometer in the console
:author:            Harald Pehl
:email:             hpehl@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.redhat.com/browse

== Overview

The goal of this RFE is to support the configuration of the Micrometer subsystem in the management console.

=== User Stories

As a WildFly administrator, I want to configure the Micrometer subsystem through the management console so that I can manage the observability settings.

== Issue Metadata

=== Related Issues

* {issue-base-url}/HAL-1843
* {issue-base-url}/EAP7-1686
* {issue-base-url}/WFLY-17144
* {issue-base-url}/WFLY-14947
* {issue-base-url}/EAP7-2053

=== Affected Projects or Components

This RFE affects the management console (https://github.com/hal/console[HAL]).

=== Other Interested Projects

None.

=== Relevant Installation Types

* Traditional standalone server (unzipped or provisioned by Galleon)
* Managed domain

== Requirements

The console shows the subsystem `micrometer` in the configuration section under Configuration / Subsystems / Micrometer. The affected resource is `/subsystem=micrometer`.

The UI for this subsystem is backed by the https://hal.github.io/documentation/concepts/#applications[model browser] which generates the UI based on the resource descriptions.

=== Non-Requirements

The console does not offer a dedicated UI to configure the `micrometer` subsystem.

=== Future Work

A dedicated UI to configure the `micrometer` subsystem might be added in a future RFE.

== Backwards Compatibility

This feature adds new UI for a subsystem. There are no backwards compatibility concerns.

=== Default Configuration

No changes to the default configuration.

=== Importing Existing Configuration

No impact on importing existing configuration.

=== Deployments

No impact on deployments.

=== Interoperability

No impact on interoperability.

== Admin Clients

This feature is the admin console (HAL) implementation itself. No additional follow-up work is required in admin clients.

== Security Considerations

There are no security implications. The console relies on the existing management security infrastructure.

[[test_plan]]
== Test Plan

Additional tests are added to the test suite that verifies that the relevant resources can be configured. This includes automated integration tests that verify the Micrometer subsystem configuration is accessible and modifiable through the console.

== Community Documentation

See the official HAL website at https://hal.github.io

== Release Note Content

The WildFly management console (HAL) now supports configuring the Micrometer subsystem. The configuration is available under Configuration / Subsystems / Micrometer.
