---
categories:
  - console
  - microprofile
  - transactions
issue: https://github.com/wildfly/wildfly-proposals/issues/784
---

= Support MicroProfile LRA in the console
:author:            Harald Pehl
:email:             hpehl@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.redhat.com/browse


== Overview

The goal of this RFE is to support the configuration and runtime aspects of the MicroProfile LRA spec in the management console.
{issue-base-url}/WFLY-14869[WFLY-14869] introduces two new subsystems: `microprofile-lra-coordinator` and
`microprofile-lra-participant`.
This RFE adds support for these two subsystems in the console.

== Issue Metadata

=== Issue

* {issue-base-url}/HAL-1842

=== Related Issues

* {issue-base-url}/EAP7-1496
* {issue-base-url}/WFLY-14869
* {issue-base-url}/WFLY-19872
* {issue-base-url}/EAP7-2051

=== Dev Contacts

* mailto:{email}[{author}]

=== QE Contacts

* mailto:kstekovi@redhat.com[Krystof Stekovic]

=== Testing By

* [ ] Engineering
* [x] QE

=== Affected Projects or Components

This RFE affects the management console.
It depends on the management resources defined by {issue-base-url}/WFLY-14869[WFLY-14869].

== Requirements

Affected UI::
* Configuration / Subsystems / MicroProfile LRA Coordinator
* Configuration / Subsystems / MicroProfile LRA Participant
Affected Resources::
* `microprofile-lra-coordinator`
* `microprofile-lra-participant`

=== Hard Requirements

The console shows the new subsystems `microprofile-lra-coordinator` and `microprofile-lra-participant` in the configuration
section. The UI for these subsystems is backed by the https://hal.github.io/documentation/concepts/#applications[model browser]
which generates the UI based on the resource descriptions.

=== Non-Requirements

The console does not offer a dedicated UI to configure the `microprofile-lra-coordinator` and `microprofile-lra-participant`
subsystems.

=== Future Work

A dedicated UI to configure the `microprofile-lra-coordinator` and `microprofile-lra-participant` subsystems might be added
in a future RFE.

== Open Questions

* None

== Test Plan

Additional tests are added to the test suite that verifies that the relevant resources can be configured.

== Community Documentation

See the official HAL website at https://hal.github.io
