---
categories:
  - console
  - user-experience
---
= Customise Browser Title
:author:            Harald Pehl
:email:             hpehl@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.redhat.com/browse

== Overview

Customise the title of the management console. A custom title can be specified in the user settings of the console. The title can contain the following placeholders:

- `%n`: The `name` attribute of the the root resource
- `%o`: The `organization` (standalone) resp. `domain-organization` attribute of the the root resource

If the title is not specified, the built in title will be used. If a placeholder is used, but the attribute is undefined, the built in title will be used.
The built in title defaults to "%n | Management Console".

== Issue Metadata

=== Issue

* {issue-base-url}/HAL-1578[HAL-1578]

=== Related Issues

* {issue-base-url}/EAP7-837[EAP7-837]

=== Dev Contacts

* mailto:hpehl@redhat.com[Harald Pehl]

=== QE Contacts

* mailto:jkasik@redhat.com[Jan Kasik]

=== Testing By
    
[ ] Engineering
    
[x] QE

=== Affected Projects or Components

* WildFly
* HAL

== Requirements

- Add an entry in the user setting to customise the title
- If no title is specified the built in title will be used
- If a title is specified use this title as browser / tab title
- Replace `%n` with the value of the `name` attribute of the root resource
- Replace `%o` with the value of the `organization` (standalone) resp. `domain-organization` (domain) attribute of the root resource
- If a placeholder resolves to an undefined attribute use the built in title.
- If the `name`, `organization` or `domain-organization` attributes are modified, the console has to be reloaded to reflect the changes in the title.

== Test Plan

TBD

== Community Documentation

See the official HAL website at https://hal.github.io
