= Configure enable-amq1-prefix Attribute
:author:            Harald Pehl
:email:             hpehl@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.redhat.com/browse

== Overview

Add option to automatically add/update passwords in a credential store when creating/updating a datasource in the HAL console.

== Issue Metadata

=== Issue

* {issue-base-url}/HAL-1710[HAL-1710]
* {issue-base-url}/EAP7-1552[EAP7-1552]

=== Related Issues

* {issue-base-url}/WFLY-12218[WFLY-12218]
* {issue-base-url}/WFCORE-4150[WFCORE-4150]

=== Dev Contacts

* mailto:hpehl@redhat.com[Harald Pehl]

=== QE Contacts

* mailto:msvehla@redhat.com[Martin Svehla]

=== Testing By

[x] Engineering

[ ] QE

=== Affected Projects or Components

* WildFly
* HAL

== Requirements

When creating a new datasource in HAL, there must be an option to automatically add the specified password to an existing credential store by entering the store name and credential alias and plaintext password. The datasource is then created with a reference to the credential store.

Affected UI:: Configuration / Subsystems / Datasources
Affected Resources:: `/subsystem=datasources/data-source=*`

== Test Plan

Additional tests are added to the test suite that verify that a new data source is created with a reference to a credential store.

== Community Documentation

See the official HAL website at https://hal.github.io
