= CLOUD-3496, S2i to handle CLI scripts generated by SSO console
:author:            JF Denise
:email:             jdenise@redhat.com
:toc:               left
:icons:             font
:keywords:          openshift,galleon,layers
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.jboss.org/browse/

== Overview

The intent of this feature is to support new deployment format generated by SSO server 7.4.
User can put in _<app>/configuration/_ directory one of the files: _secure-saml-deployments.cli_ and _secure-deployments.cli_
that will be discovered by the server and used to configure SSO deployments. 

== Issue Metadata

=== Issue:

* {issue-base-url}CLOUD-3496[CLOUD-3496]
* {issue-base-url}EAP7-1379[EAP7-1379]

=== Related Issues:

* {issue-base-url}KEYCLOAK-10898[KEYCLOAK-10898]

=== Dev Contacts:

* mailto:jdenise@redhat.com[Jean-François Denise]

=== QE Contacts:

Testing done by Eng.

* mailto:jdenise@redhat.com[Jean-François Denise]

=== Affected Projects or Components:

* Openshift EAP images

== Requirements

=== Hard requirements

* Discover and use _secure-saml-deployments.cli_ and _secure-deployments.cli_ CLI script files (if present) to configure SSO OIDC and SAML subsystems.

* Legacy _secure-saml-deployments_ and _secure-deployments_ XML files are still supported.

* If both legacy XML files and CLI script files are present, CLI scripts are used. XML files are ignored. 

=== Nice to have requirements

* NONE.

== Test Plan

* New behave tests to cover usage of the 2 files.

== Community Documentation

NONE.

