= EAP7-627 RESTEasy should be able to provide trace information about request
:author:            Wei Nan Li
:email:             weli@redhat.com
:toc:               left
:icons:             font
:keywords:          comma,separated,tags
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.redhat.com/browse

== Overview

RESTEasy should be able to provide trace information about request in response headers. These trace information should be in headers if:

it is required by global settings for all application (for example by EAP7-634)
it is required by settings for one application (for example by EAP7-634)
it is required in request header (for example: curl -v --header "RESTEasy-trace: true" http://localhost:8080/jaxrs-wf/some)

Trace information should contains all necessary information and times about processing of current request, like used interceptors, used exception mappers, used end-points, used providers, etc. Example:


== Issue Metadata

=== Issue:

* {issue-base-url}/EAP7-627[EAP7-627]

=== Related Issues:

* {issue-base-url}/EAP7-634[EAP7-634]
* {issue-base-url}/EAP7-627[EAP7-606]

=== Dev Contacts:

* mailto:jperkins@redhat.com[James Perkins]
* mailto:asoldano@redhat.com[Alessio Soldano]
* mailto:rsigal@redhat.com[Ron Sigal]
* mailto:separdau@redhat.com[Stephane Epardaud]
* mailto:ema@redhat.com[Jim Ma]
* mailto:rsearls@redhat.com[Rebecca Searls]
* mailto:weli@redhat.com[Wei Nan Li]

=== QE Contacts:


=== Affected Projects or Components:

* WildFly
* RESTEasy

== Requirements


=== Test Plan

The features are heavily tested in RESTEasy codebase. Successfully running the latest RESTEasy release' testsuite against target WildFly container will be required.


== Community Documentation

The documentation is coming with the release of the RESTEasy.


