= Expose JAX-RS Resources to gRPC clients
:author:            Ron Sigal
:email:             rsigal@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.jboss.org/browse

== Overview

In the five years since gRPC was introduced, it has become a popular invocation
and streaming framework, used by major corporations. Among its benefits are

* speed
* language independence

With this feature request we propose to expose JAX-RS services as gRPC services,
accessible by gRPC clients.

Given a gRPC service definition like
----
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
----

the protobuf java compiler will create a class GreeterGrpc, and a service can be
created by subclassing. We envision making it as easy as something like this
to forward a gRPC request to JAX-RS:

----

static class GreeterImpl extends GreeterGrpc.GreeterImplBase {

   public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver) {
      JAXRSForwarderBuilder builder = new JAXRSForwarderBuilder();
      builder.servlet("ResteasyServlet").pathTranslator((String s) -> ("test/" + s));
      JAXRSForwarder forwarder = builder.build();
      forwarder.forward(req, (StreamObserver) responseObserver);
   }
}
----

The JAXRSForwarder will find the appropriate servlet, create the appropriate HTTP
requests and responses, call the JAX-RS resource method, and send
the result to the gRPC StreamObserver. 

== Issue Metadata

=== Issue

* {issue-base-url}/EAP7-1536 [EAP7-1536]
* {issue-base-url}/WFLY-13530 [WFLY-13530]


=== Related Issues

* {issue-base-url}/PRODMGT-1811 [PRODMGT-1811]
* {issue-base-url}/WFLY-11034 [WFLY-11034]
* {issue-base-url}/RESTEASY-2656 [RESTEASY-2656]

=== Dev Contacts

* mailto:rsigal@redhat.com[Ron Sigal]
* mailto:asoldano@redhat.com[Alessio Soldano]
* mailto:ema@redhat.com[Jim Ma]
* mailto:rsearls@redhat.com[Rebecca Searls]
* mailto:weli@redhat.com[Wei Nan Li]
* mailto:jperkins@redhat.com[James Perkins]

=== QE Contacts

* Martin Svehla

=== Testing By

TBD

* [ ] Engineering

* [ ] QE

=== Affected Projects or Components

* RESTEasy
* Wildfly

=== Other Interested Projects

* Elytron. "[A]ny security requirements will be handled with Elytron exclusively." -Darren Lofthouse

== Requirements

=== Hard Requirements

* A gRPC server will be exposed on its own port.
* RESTEasy will create a map matching servlet names to RESTEasy servlets, which will be used to
  select a JAX-RS resource to be used to satisfly a gRPC request. 
* Each gRPC request needs to be matched to a JAX-RS resource method. In the simplest case
** the name of the appropriate servlet will be based on the name of the gRPC server.
** the JAX-RS resource will have been constructed to match the HTTP verb and path generated by gRPC.

=== Nice-to-Have Requirements

* The basic case described under "Hard Requirements" requires the JAX-RS resource to be constructed
  to match the gRPC server. In order to be able to expose pre-existing JAX-RS, we propose to
  define a translating facility that can translate from the gRPC request to a JAX-RS resource. See
  the JAXRSForwarderBuilder mentioned in the introduction.
  
* We could hard code a port number, but it would be desirable to add a configurable RESTEasy
  parameter. That parameter should be exposed by the jaxrs module.

=== Non-Requirements

* Ideally, the gRPC server, which runs on Netty, would be able to share a port with other
  Netty services. It is expected that Undertow 3 will support Netty port sharing when it becomes
  available, which probably won't occur in time for EAP 7.4.

== Test Plan

* We would want to include tests in the RESTEasy testsuite. These would test a variety of gRPC
  services which implement both discrete and streaming requests and responses.
  
* The jaxrs module tests would be extended to include the gRPC port parameter.

== Community Documentation

We will write a chapter in the RESTEasy User Guide.

== Release Note Content

JAX-RS resources can now be accessed by gRPC clients.
