= WFLY-11943 / Statistics of REST endpoints
:author:            Rebecca Searls
:email:             rsearls@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.jboss.org/browse

== Overview

Collect and report runtime statistics on REST endpoints running in RESTEasy.

=== Project Scope

Statistics reporting by Wildfly components (e.g. clustering, connector, ejb3, undertow)
has existed from before Wildfly 7.0.0.Final.  The earliest introduction of this
feature into Wildfly has not been found.  The feature defines XML attribute,
`statistics-enabled` used in subsystem definitions to declare the default setting
for data collection, and it is used in the CLI to turn on and off data collection,
This feature also provides command `reset-statistics` to clear collected data and start a new.
This RFE is adding component jaxrs to the set of reporting components using this feature.

This RFE will not use or replace undertow's statistics data.  Endpoint data from
within RESTeasy is reported.

=== Not Project Scope

This RFE is NOT related to Eclipse MicroProfile Metrics nor to the microprofile-metrics-smallrye.

== Issue Metadata

=== Issue

* {issue-base-url}/WFLY-11943[WFLY-11943]
* {issue-base-url}/EAP7-606[EAP7-606]

=== Related Issues

* https://issues.jboss.org/browse/WFLY-11751[WFLY-11751]
* https://issues.jboss.org/browse/WFLY-12091[WFLY-12091]

=== Dev Contacts

* mailto:rsearls@redhat.com[Rebecca Searls]
* mailto:rsigal@redhat.com[Ron Sigal]
* mailto:asoldano@redhat.com[Alessio Soldano]
* mailto:ema@redhat.com[Jim Ma]
* mailto:weli@redhat.com[Wei Nan Li]

=== QE Contacts

* mailto:mkopecky@redhat.com[Marek Kopecky]

=== Testing By
// Put an x in the relevant field to indicate if testing will be done by Engineering or QE. 
// Discuss with QE during the Kickoff state to decide this
[X] Engineering

[ ] QE

=== Affected Projects or Components

* WildFly
* RESTEasy

=== Other Interested Projects

* HAL
* CLI

== Requirements

* Collect endpoint statistics when instructed by Wildfly.
* Report accumulated statistics when requested by Wildfly.
* Reset endpoint statistics when instructed by Wildfly.
* Stop data collection and clear accumumlated data when instructed by Wildfly.
* Subsystem attribute `statistics-enabled` will be used to start and stop statistics collection.  Default setting is false.  The default value can be declared to `true` in the Wildfly configuration file, jaxrs subsystem element.
* Subsystem operation `read-resource` will display the statistics for each endpoint.
* Subsystem operation `reset` will reset collected statistics to zero.
* Application restart is NOT required when enabling, disabling and resetting statistics collection.
* Statistics are NOT save on application restart.

=== Hard Requirements
* Statistics provided
** `invocation-count` - Total count of calls to endpoint
** `failed-invocation-count` - Number of endpoint calls that failed.
Fail here means exception thrown. A response object returning any
status is not considered a failure in this case.
** `average-execution-time` - The average time in nanosec from the point of endpoint invocation to return.
** `total-execution-time` - The sum of time in nanosec for all endpoint method invocations.

=== Non-Requirements

* A best effort will be made to report accurate data.  Any lag between report request and data display could provide statistics that are slightly out of date.

* This project is not responsible for the display of the data.  A report request will write the data into Wildfly's reference model for access by other components.

== Test Plan
One or more test case classes will be added to wildfly/testsuite/integration/basic.
A test will be provided for each of the following.

* Confirm subsystem attribute, statistics_enabled, can be read and written.
* Confirm correct invocation-cnt returned on endpoint.
* Confirm correct failure-cnt returned on endpoint.
* Confirm statistics provided for each endpoint declared in a resource class.
* Confirm statistics provided on all endpoints in an app with multiple resource classes.
* Confirm statistics reset command works.

Tests of this feature in HAL and CLI are not provided.

== Community Documentation
This feature uses the existing commands and attribute of wildfly metrics
and thus does not need separate documentation.
