---
# Add any category for this proposal as a YAML list, e.g.
# - core
# - management
# If missing, add it to _data/wildfly-categories and use its id
categories:
- undertow
- ejb
# Specify the stability level of the feature.
# Values can be one of: experimental, preview, community, or default
stability-level: default
# Specify the Feature Development tracker issue for the feature.
# This must be an issue tracked in https://github.com/orgs/wildfly/projects/7/views/1.
# To create a Feature Development tracker issue, go to https://github.com/wildfly/wildfly-proposals/issues/new/choose
# and select 'Feature Development'
issue: https://github.com/wildfly/wildfly-proposals/issues/732
# Provide the GitHub ids of the feature team members, organized by role.
# Provide a single id for the 'assignee' role. Use a YAML list for the 'sme' and
# 'outside-perspective' roles, even if there is only one person in a role.
feature-team:
 developer: jasondlee
 sme:
  -
 outside-perspective:
  -
# If this issue tracks the promotion of a previously completed feature to a higher stability level, provide the URL of
# the original https://github.com/wildfly/wildfly-proposals/issues issue that was used to track the implementation of
# that feature.
promotes:
# During initial development of a feature, this field should be left blank. If after the feature is completed and its
# stability level is promoted via a later issue, the developer promoting the issue should return to this document ("this"
# being the original analysis document for the feature). The field should be updated to point to the
# https://github.com/wildfly/wildfly-proposals/issues issue that promotes it.
# For example,
#              | Implementation Issue (A) | Promotion Issue (B)
# promotes:    |                          | https://github.com/.../A
# promoted-by: | https://github.com/.../B |
promoted-by:
---

= Support TCP_NODELAY in wildfly-config.xml
:author:            Jason Lee
:email:             jasondlee@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

__<The entire document should be one to two pages long. We will write each analysis document as if it is a conversation
with a future developer. This requires a good writing style, with full sentences organized into paragraphs. Bullets are
acceptable only for visual style, not as an excuse for writing sentence fragments.>__

== Overview

A number of socket options are not configurable, in particular `TCP_NODELAY`. This leads, in some cases, to unacceptable performance
characteristics. To remedy this, `WildFlyHttpContext` and its related XML schema need to be updated to allow these options to being
configured either programmatically or via XML config.

=== User Stories

__<Provide one or more brief user stories that illustrate the intended users of the feature and the goal they will seek
to achieve by using the feature.>__

As an application developer, I would like greater flexibilty in configuring the socket used by the HTTP EJB client.

== Issue Metadata

* https://issues.redhat.com/browse/WEJBHTTP-154

=== Related Issues

__<List the issues related to this feature>__

=== Affected Projects or Components

__<List the projects or components that are affected by the feature. List them using their Git repositories.>__

=== Other Interested Projects

* Undertow
* EJB

=== Relevant Installation Types

__<List the installation types that are relevant for the features and remove any that are not relevant>__.

* Traditional standalone server (unzipped or provisioned by Galleon)
* Managed domain
* OpenShift Source-to-Image (S2I)
* Bootable jar

== Requirements

__<Describe the requirements that must be fulfilled by this feature.>__

__<For analyses of a promotion of an existing feature to 'preview' or 'community' stability, only list new requirements;
existing requirements from the feature being promoted are assumed to continue unless otherwise noted in the 'Changed
requirements' section. Other analyses, including those for promotion to the 'default' stability level, must list all
requirements.>__

* The `wildfly-http-client` schema version should be modified to add additional elements, including but not limited to
  (exact list to be finalized before this document is merged):
  * TCP_NODELAY

=== Changed requirements

N/A

=== Non-Requirements

N/A

=== Future Work

N/A

== Backwards Compatibility

This change will include a new version of the XML schema, but the old version will still be fully supported. There should
not, then, be any bacwards compatibility issues.

=== Default Configuration

There will be no default configuration changes. Any added elements/properties will default to their current, unconfigured values.

=== Importing Existing Configuration

Existing configurations will continue to work unchanged.

=== Deployments

Unless deployments opt in to use the new schema version, they will be unaffected by this change.

=== Interoperability

There are no interop issues foreseen.

== Implementation Plan

N/A

== Admin Clients

N/A

== Security Considerations

There no security considerations foreseen.

[[test_plan]]
== Test Plan

__<Depending on the selected stability level, the appropriate section below should be completed, including a brief
description of how testing is to be performed in accordance with the selected stability level. The non-relevant sections
may be removed as needed.>__
////
Depending on the stability level, the test plan required may vary. See below.
////

** Experimental - No test plan is required. Basic unit / integration tests should be added during development.

** Preview - a brief high-level description of the testing approach should be added here, including types of tests added
(unit, integration, smoke, component, subsystem, etc.) Note that not all test types are required for a particular feature,
so include a description of what is being tested and the approach chosen to perform the testing.

** Community - this level should include everything in the 'Preview' stability level, plus the following additional testing as relevant:
*** Manual tests: briefly describe checks to be performed during one-time exploratory testing. The purpose of this testing
is to check corner cases and other cases that are not worth implementing as automated tests. Typical checks are: bad
configurations are easy to reveal, attribute descriptions and error messages are clear, names are descriptive and consistent
with similar resources, default values are reasonable. If there is an existing quickstart affected by the feature, manual
checks include following the quickstart's guide and verifying functionality.
*** Miscellaneous checks: Manual checks for significant changes in server performance, memory and disk footprint should
be described here. These checks are not always relevant, but consideration of these impacts, and others, are strongly
encouraged and should be described here. Fully qualified test case names should be provided along with a brief description
of what the test is doing.
*** Integration tests - At the 'Community' stability level, complete integration tests should be provided.
*** Compatibility tests - If backwards compatibility is relevant to the feature, then describe how the testing is performed.
** Default - This stability level is reserved and requires approval by a professional Quality Engineer with subject matter expertise.

== Community Documentation

...

== Release Note Content

Updates have been made to the `wildfly-http-client` schema and `WWildFlyHttpContext` to allow for greater flexibilty in configuring
the socket used by the EJB client.
