---
# Add any category for this proposal as a YAML list, e.g.
# - core
# - management
# If missing, add it to _data/wildfly-categories and use its id
categories:
  - undertow
# Specify the stability level of the feature.
# Values can be one of: experimental, preview, community, or default
stability-level: preview
# Specify the Feature Development tracker issue for the feature.
# This must be an issue tracked in https://github.com/orgs/wildfly/projects/7/views/1.
# To create a Feature Development tracker issue, go to https://github.com/wildfly/wildfly-proposals/issues/new/choose
# and select 'Feature Development'
issue: https://issues.redhat.com/browse/WFLY-20650
# Provide the GitHub ids of the feature team members, organized by role.
# Provide a single id for the 'assignee' role. Use a YAML list for the 'sme' and
# 'outside-perspective' roles, even if there is only one person in a role.
feature-team:
 developer: bbaranow@redhat.com
 sme:
  - frainone@redhat.com
 outside-perspective:
  - thofman@redhat.com
# If this issue tracks the promotion of a previously completed feature to a higher stability level, provide the URL of
# the original https://github.com/wildfly/wildfly-proposals/issues issue that was used to track the implementation of
# that feature.
promotes:
# During initial development of a feature, this field should be left blank. If after the feature is completed and its
# stability level is promoted via a later issue, the developer promoting the issue should return to this document ("this"
# being the original analysis document for the feature). The field should be updated to point to the
# https://github.com/wildfly/wildfly-proposals/issues issue that promotes it.
# For example,
#              | Implementation Issue (A) | Promotion Issue (B)
# promotes:    |                          | https://github.com/.../A
# promoted-by: | https://github.com/.../B |
promoted-by:
---

= Make reuseXForwarded and rewriteHostHeader configurable in modcluster
:author:            Bartosz Baranowski
:email:             bbaranow@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

__<The entire document should be one to two pages long. We will write each analysis document as if it is a conversation
with a future developer. This requires a good writing style, with full sentences organized into paragraphs. Bullets are
acceptable only for visual style, not as an excuse for writing sentence fragments.>__

== Overview

This is follow up to https://issues.redhat.com/browse/WFLY-14255[WFLY-14255] based on https://issues.redhat.com/browse/EAPSUP-1873[EAPSUP-1873].
modcluster proxy definition should also have reuseXForwarded and rewriteHostHeader attributes configurable.


=== User Stories

__<Provide one or more brief user stories that illustrate the intended users of the feature and the goal they will seek
to achieve by using the feature.>__

== Issue Metadata

=== Related Issues

https://issues.redhat.com/browse/WFLY-14255[WFLY-14255]
https://issues.redhat.com/browse/EAPSUP-1873[EAPSUP-1873]


=== Affected Projects or Components

 - wildfly-undertow

=== Other Interested Projects

=== Relevant Installation Types

__<List the installation types that are relevant for the features and remove any that are not relevant>__.

* Traditional standalone server (unzipped or provisioned by Galleon)
* Managed domain
* OpenShift Source-to-Image (S2I)
* Bootable jar

== Requirements

Add ability to configure reuseXForwarded and rewriteHostHeader in mod cluster filter definition: /subsystem=undertow/configuration=filter/mod_cluster=custom_proxy

=== Changed requirements

__<Only relevant for analyses of a promotion of an existing feature to 'preview' or 'community stability. Other analyses
should remove this section.>__

__<For any existing requirements from the feature being promoted that are being changed or removed, describe the change.>__


=== Non-Requirements

__<Use this section to explicitly discuss things that readers might think are required but which are not required.>__

=== Future Work

__<Use this section to discuss requirements that are not addressed by this proposal but which may be addressed in later proposals.>__

== Backwards Compatibility

Should not be a problem, default values of new attributes align with current values in code.

=== Default Configuration

No, defaults align with existing values in code.

=== Importing Existing Configuration

No.

=== Deployments

__<Does this feature change the behavior of deployments in incompatible ways? If yes, please detail what is the deployment
issue observed when no change is done, and what is the change needed to solve the deployment issue.>__

=== Interoperability

__<Is this feature impacting interoperability?>__

== Implementation Plan

__<This section is optional. If you have a complex feature which cannot be delivered all in one go, suggest the strategy.>__

== Admin Clients

Unless HAL derives config options from model description, it will need patch to include new attributes.

== Security Considerations

X-Forwarded headers need to be used with care: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-Forwarded-For[X-Forwarded-For security risk]

[[test_plan]]
== Test Plan

Subsystem tests are part of component and with update will include this change.
////
Depending on the stability level, the test plan required may vary. See below.
////

** Experimental - No test plan is required. Basic unit / integration tests should be added during development.

** Preview - a brief high-level description of the testing approach should be added here, including types of tests added
(unit, integration, smoke, component, subsystem, etc.) Note that not all test types are required for a particular feature,
so include a description of what is being tested and the approach chosen to perform the testing.

** Community - this level should include everything in the 'Preview' stability level, plus the following additional testing as relevant:
*** Manual tests: briefly describe checks to be performed during one-time exploratory testing. The purpose of this testing
is to check corner cases and other cases that are not worth implementing as automated tests. Typical checks are: bad
configurations are easy to reveal, attribute descriptions and error messages are clear, names are descriptive and consistent
with similar resources, default values are reasonable. If there is an existing quickstart affected by the feature, manual
checks include following the quickstart's guide and verifying functionality.
*** Miscellaneous checks: Manual checks for significant changes in server performance, memory and disk footprint should
be described here. These checks are not always relevant, but consideration of these impacts, and others, are strongly
encouraged and should be described here. Fully qualified test case names should be provided along with a brief description
of what the test is doing.
*** Integration tests - At the 'Community' stability level, complete integration tests should be provided.
*** Compatibility tests - If backwards compatibility is relevant to the feature, then describe how the testing is performed.
** Default - This stability level is reserved and requires approval by a professional Quality Engineer with subject matter expertise.

== Community Documentation

Having simply paragraph dedicated to highlight of fact that mod_cluster and regular proxy support those options. Also, note about possible exploitation of X-Forwarded-For might be warranted.

== Release Note Content

__<Draft verbiage for up to a few sentences on the feature for inclusion in the Release Note blog article for the release
that first includes this feature.__
__Example article: https://www.wildfly.org/news/2024/01/25/WildFly31-Released/.__
__This content will be edited, so there is no need to make it perfect or discuss what release it appears in.>__
