= WFLY-11764 Make return value of HttpServletRequest.getServletPath/getRequestURI/getRequestURL configurable (DeploymentInfo.setPreservePathOnForward)
:author:            Flavia Rainone
:email:             frainone@redhat.com
:toc:               left
:icons:             font
:keywords:          getServletPath,getRequestURI,getRequestURL,preserve path,HttpServletRequest
:idprefix:
:idseparator:       -

== Overview

This feature is to support a backwards compatible behavior of `HttpServletRequest.getServletPath` in Undertow.

In an Struts2 application deployed to EAP6, this method returns the action name, but in EAP7 it returns the
forwarded jsp name.

Undertow's `DeploymentInfo` API was updated to support that behavior (via `DeploymentInfo.setPreservePathOnForward`)
and now we need to make that behavior configurable in EAP7.
Notice that, for consistency reasons, the returned value of `HttpServletRequest.getRequestURI` and
`HttpServletRequest.getRequestURL` are also affected by the same configuration, making them return the URI/URL with
the action name if `DeploymentInfo.preservePathOnForward` is set to `true`.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFLY-11764[WFLY-11764]

=== Related Issues

* https://issues.jboss.org/browse/EAP7-1341[EAP7-1341]
* https://issues.jboss.org/browse/JBEAP-17141[JBEAP-17141]
* https://issues.jboss.org/browse/UNDERTOW-1159[UNDERTOW-1159]
* https://issues.jboss.org/browse/UNDERTOW-1499[UNDERTOW-1499]
* https://issues.jboss.org/browse/UNDERTOW-1504[UNDERTOW-1504]
* https://issues.jboss.org/browse/JBEAP-16448[JBEAP-16448]
* https://issues.jboss.org/browse/JBEAP-16449[JBEAP-16449]



=== Dev Contacts

* mailto:{email}[{author}]
* mailto:bspyrkos@redhat.com[Bartosz Spyrko-Smietanko]

=== QE Contacts

* mailto:jstourac@redhat.com[Jan Stourac]

=== Testing By
// Put an x in the relevant field to indicate if testing will be done by Engineering or QE. 
// Discuss with QE during the Kickoff state to decide this
[X] Engineering

[ ] QE

=== Affected Projects or Components

* WildFly, Undertow component
* Undertow

=== Other Interested Projects


== Requirements

This will be implemented as an additional attribute under the `/subsystem=undertow/servlet-container=<name>` management
model address.

This will be a simple boolean attribute called `preserve-path-on-forward` that marks the path to be preserved or not.
The default value must be `false` to keep backwards compatibility to Undertow's previous versions and to keep 
compatibility with the default in the tech preview, i.e, in
https://github.com/jbossas/jboss-eap7/pull/2977/files#diff-ec283754699197fecae93a21443427b9R86[JBEAP-16448 PR]


=== Hard Requirements

=== Nice-to-Have Requirements

=== Non-Requirements

== Test Plan

A new test will be added to verify that `HttpServletRequest.getServletPath`, `HttpServletRequest.getRequestURI`,
and `HttpServletRequest.getRequestURL` all return a preserved path on forward if `preserve-path-on-forward` is set to
`true`.

== Community Documentation

Update the WildFly documentation to document the new attribute, and the affected behavior.
